[build]
  publish = "public"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/favicons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/webfonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Optional safeguard: Prevent manual Content-Encoding interference
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = ""
