module.exports = {
	en: {
		title: "Driven by Passion: Transforming Cars into Art",
		introText1: "As a lifetime car enthusiast and avid photographer, I combine my passion for cars with my love for photography to create stunning images. I specialize in capturing the unique character of each vehicle, from classic beauties to modern marvels.",
		introText2: "Whether you're a car owner wanting to showcase your prized possession or a business seeking captivating automotive imagery, I'm here to bring your vision to life.",
		portfolioTitle: "My Automotive Photography Portfolio",
		portfolioProfessional: "Professional Commercial Work",
		portfolioProjects: "Personal Beauty Shoot Projects",
		portfolioUsed: "Used Car Photography",
		servicesTitle: "Tailored Car Photography Services for Every Need",
		servicesText: "I understand that every car and every client is unique, which is why I offer a range of tailored car photography services to meet your specific needs. Whether you're looking for artistic beauty shots, professional images to sell a used car, or high-impact photos for your automotive event, I've got you covered. My goal is to provide you with stunning visuals that capture the essence and value of your vehicle, whatever the purpose.",
		service1Title: "Beauty Shoots",
		service1Price: "Starts at 100.00 EUR",
		service1Tagline: "High-quality, artistic shots of cars, perfect for enthusiasts and collectors.",
		service1Text: "My beauty shoots are all about showcasing your car in the best possible light. They're perfect for car enthusiasts and collectors who want to highlight the unique features and beauty of their vehicles. I pay close attention to detail, capturing the sleek lines, luxurious interiors, and every element that makes your car special. These images are not just photos; they are works of art that you can treasure and share with fellow car lovers.",
		service2Title: "Used Car Photography",
		service2Price: "100.00 EUR",
		service2Tagline: "Simple yet effective photography to help sell used cars quickly.",
		service2Text: "Selling a used car? Professional photography can make a huge difference. I focus on capturing clear, attractive images that highlight the car's condition and features, making it more appealing to potential buyers. Good photos can help you sell your car faster and at a better price. I'll make sure your car looks its best, helping you stand out in a competitive market. You'll receive 8-12 photos that you can upload to used car websites right away!",
		service3Title: "Event Photography",
		service3Price: "From 25.00 EUR/hr",
		service3Tagline: "Comprehensive and meaningful documentation of your automotive event.",
		service3Text: "Whether it's a car show, a club meet, or a large-scale automotive event, I provide full photo coverage that brings the event to life. My event photography not only showcases the stunning cars on display but also captures the human interactions and the excitement of the event. With a keen eye for detail and a background in photographing people, I ensure that every shot tells a story. Perfect for event organizers, automotive fans and participants.",
		contactTitle: "Ready to Transform Your Car's Image?",
		contactText: "Are you ready to give your car the spotlight it deserves? Whether you need stunning beauty shots, effective used car photos, or high-impact brand images, I'm here to help. Contact me today to discuss your project and see how we can make your car shine. Let's create something amazing together!",
		contactButton: "Let's Create!",
	},
	hu: {
		title: "Autó Fotózás Szakszerűen, Szenvedéllyel",
		introText1: "Életre szóló autórajongóként és lelkes fotósként egyesítem az autók iránti szenvedélyemet a fényképezés szeretetével, hogy lenyűgöző képeket készítsek. Arra specializálódtam, hogy megragadjam minden egyes jármű egyedi karakterét, legyen szó klasszikus szépségekről vagy modern csodákról.",
		introText2: "Akár büszke autótulajdonos vagy, aki profi képeket szeretne a nagy becsben tartott autójáról, akár cég, aki vonzó autós képeket szeretne az eladásra kínált autóikról, azért vagyok itt, hogy életre keltsem az elképzeléseidet.",
		portfolioTitle: "Autó Fotózás Portfólióm",
		portfolioProfessional: "Profi Autó Fotózás Cégeknek",
		portfolioProjects: "Autó Szépség Fotózások",
		portfolioUsed: "Profi Használt Autó Fotózás",
		servicesTitle: "Testreszabott Autó Fotózás Minden Igényre",
		servicesText: "Tudom, hogy minden autó és minden ügyfél egyedi, ezért különféle testreszabott autófotózási szolgáltatásokat kínálok. Legyen szó művészi szépségfotókról, kiváló minőségű képekről egy használt autó eladásához, vagy a fontos pillanatokat megörökítő autós esemény fotókról, szívesen segítek. Az a célom, hogy lenyűgöző vizuális anyagokat készítsek, amelyek megragadják autóid lényegét és értékét, bármilyen célra is legyen szükséged rájuk.",
		service1Title: "Autó Szépség Fotózás",
		service1Price: "25.000 Ft-tól",
		service1Tagline: "Kiváló minőségű, művészi autó fotózás, a rajongók és gyűjtők választása.",
		service1Text: "A szépség fotózások célja, hogy autódat a lehető legjobb fényben mutassam be. Ezek a fotók tökéletesek az autórajongók és gyűjtők számára, akik szeretnék kiemelni járművük egyedi szépségét. Nagy figyelmet fordítok a részletekre, megörökítve az elegáns vonalakat, a csodás belső tereket és minden olyan elemet, amely különlegessé teszi autódat. Ezek a képek nem csupán fotók, hanem művészeti alkotások, amelyeket büszkén oszthatsz meg más autórajongókkal.",
		service2Title: "Használt Autó Fotózás",
		service2Price: "25.000 Ft",
		service2Tagline: "Gyorsan profi képeket készítünk használt autódról, hogy könnyebben el tudd adni.",
		service2Text: "El szeretnéd adni használt autódat? A profi fotózás óriási különbséget jelenthet. Célom, hogy letisztult, kívánatos fotókat készítsek, amelyek kiemelik az autó állapotát és jellemzőit, vonzóbbá téve azt a potenciális vásárlók számára. A jó fotók segíthetnek gyorsabban és jobb áron eladni autódat. Garantálom, hogy a fotóimon az autód a lehető legjobban fog kinézni, segítve abban, hogy kitűnj a többi hirdetés közül. 8-12 fotót kapsz, amelyeket azonnal feltölthetsz a használt autós weboldalakra!",
		service3Title: "Esemény Fotózás",
		service3Price: "10.000 Ft/órától",
		service3Tagline: "Autós-motoros események átfogó, jelentőségteljes dokumentálása.",
		service3Text: "Legyen szó autókiállításról, klubtalálkozóról vagy nagyszabású autóipari eseményről, teljes körű fotóközvetítést biztosítok, amely életre kelti az eseményt. A rendezvényfotózásom nemcsak a kiállított lenyűgöző autókat mutatja be, hanem az emberi interakciókat és az esemény izgalmát is megörökíti. A részletek iránti éles szememmel és az emberek fényképezésében szerzett tapasztalataimmal gondoskodom arról, hogy minden felvétel egy történetet meséljen el. Tökéletes rendezvényszervezők, autórajongók és résztvevők számára.",
		contactTitle: "Emeld Új Szintre Autód Megjelenését",
		contactText: "Készen állsz, hogy autód megkapja a megérdemelt figyelmet? Legyen szó lenyűgöző szépségfotókról, hatékony használt autó fotózásról, vagy nagy hatású márka fotókról, én készen állok. Vedd fel velem a kapcsolatot még ma, és megbeszéljük a részleteket. Alkossunk valami csodálatosat együtt!",
		contactButton: "Készítsünk Autós Fotókat!",
	},
};
