module.exports = {
	en: {
		title: "Driven by Passion: Transforming Cars into Art",
		introText1: "As a lifetime car enthusiast and avid photographer, I combine my passion for cars with my love for photography to create stunning images. I specialize in capturing the unique character of each vehicle, from classic beauties to modern marvels.",
		introText2: "Whether you're a car owner wanting to showcase your prized possession or a business seeking captivating automotive imagery, I'm here to bring your vision to life.",
		onThisPage: "On this page:",
		subtitle1: "Why Choose Professional Car Photography?",
		subtitle2: "My Automotive Photography Portfolio",
		subtitle3: "Tailored Car Photography Services for Every Need",
		subtitle4: "Get Started",
		whyReason1Title: "Stand Out from the Crowd",
		whyReason1Text: "Professional photos can make your car stand out in a crowded market. High-quality, well-composed images attract attention and make a lasting impression.",
		whyReason2Title: "Increase Value",
		whyReason2Text: "If you're selling your car, professional photos can increase its perceived value. Potential buyers are more likely to be drawn to a car that looks amazing in photos.",
		whyReason3Title: "Create Memories",
		whyReason3Text: "For car enthusiasts and owners, professional photography is a way to create lasting memories of your prized possession. It's more than just a photo - it's a work of art that you can treasure.",
		whyReason4Title: "Boost Marketing Efforts",
		whyReason4Text: "For dealerships and businesses, high-quality images are essential for marketing. They can be used in advertisements, social media, and websites to attract more customers and drive sales.",
		portfolioProfessional: "Professional Commercial Work",
		portfolioProjects: "Personal Beauty Shoot Projects",
		servicesText: "I understand that every car and every client is unique, which is why I offer a range of tailored car photography services to meet your specific needs. Whether you're looking for artistic beauty shots, professional images to sell a used car, or high-impact photos for a brand or dealership, I've got you covered. My goal is to provide you with stunning visuals that capture the essence and value of your vehicle, whatever the purpose.",
		service1Title: "Beauty Shoots",
		service1Tagline: "High-quality, artistic shots of cars, perfect for enthusiasts and collectors.",
		service1Text: "My beauty shoots are all about showcasing your car in the best possible light. They're perfect for car enthusiasts and collectors who want to highlight the unique features and beauty of their vehicles. I pay close attention to detail, capturing the sleek lines, luxurious interiors, and every element that makes your car special. These images are not just photos; they are works of art that you can treasure and share with fellow car lovers.",
		service2Title: "Used Car Photography",
		service2Tagline: "Simple yet effective photography to help sell used cars quickly.",
		service2Text: "Selling a used car? Professional photography can make a huge difference. I focus on capturing clear, attractive images that highlight the car's condition and features, making it more appealing to potential buyers. Good photos can help you sell your car faster and at a better price. I'll make sure your car looks its best, helping you stand out in a competitive market. You'll receive 8-12 photos that you can upload to used car websites right away!",
		service3Title: "Brand & Dealership Photography",
		service3Tagline: "Professional images to enhance marketing efforts and boost sales.",
		service3Text: "For brands and dealerships, high-quality photography is essential for marketing and sales. I provide professional images that can be used in advertisements, on websites, and across social media platforms. These photos not only showcase your vehicles but also convey the quality and reliability of your brand. Let's work together to elevate your marketing efforts and boost your business.",
		contactTitle: "Ready to Transform Your Car's Image?",
		contactText: "Are you ready to give your car the spotlight it deserves? Whether you need stunning beauty shots, effective used car photos, or high-impact brand images, I'm here to help. Contact me today to discuss your project and see how we can make your car shine. Let's create something amazing together!",
		contactButton: "Let's Create!",
	},
	hu: {
		title: "Autó Fotózás Szakszerűen, Szenvedéllyel",
		introText1: "Életre szóló autórajongóként és lelkes fotósként egyesítem az autók iránti szenvedélyemet a fényképezés szeretetével, hogy lenyűgöző képeket készítsek. Arra specializálódtam, hogy megragadjam minden egyes jármű egyedi karakterét, legyen szó klasszikus szépségekről vagy modern csodákról.",
		introText2: "Akár büszke autótulajdonos vagy, aki profi képeket szeretne a nagy becsben tartott autójáról, akár cég, aki vonzó autós képeket szeretnének az eladásra kínált autóikról, azért vagyok itt, hogy életre keltsem az elképzeléseidet.",
		onThisPage: "Ezen az oldalon:",
		subtitle1: "Miért Válassz Profi Autó Fotózást?",
		subtitle2: "Autó Fotózás Portfólióm",
		subtitle3: "Testreszabott Autó Fotózás Minden Igényre",
		subtitle4: "Vágjunk Bele!",
		whyReason1Title: "Tűnj Ki a Tömegből",
		whyReason1Text: "A profi fotók segíthetnek, hogy autód kitűnjön a zsúfolt piacon. A kiváló minőségű, jól komponált képek felkeltik a figyelmet és maradandó benyomást keltenek.",
		whyReason2Title: "Növeld az Értékét",
		whyReason2Text: "Ha el szeretnéd adni autódat, a profi fotók növelhetik annak értékét. A potenciális vásárlók szívesebben érdeklődnek egy olyan autó iránt, amely a fotókon is lenyűgözően néz ki.",
		whyReason3Title: "Őrizd meg az Emlékét",
		whyReason3Text: "Az autórajongók és tulajdonosok számára a profi fotózás egy módja annak, hogy maradandó emlékeket hozzanak létre kedvenc járművükről. Nem csak egyszerű fotókat készítünk, hanem műalkotásokat, amelyet örökre szeretni fogsz.",
		whyReason4Title: "Növeld a Marketinged",
		whyReason4Text: "Az autókereskedések és vállalkozások számára a kiváló minőségű képek elengedhetetlenek a marketingben. Használhatók hirdetésekben, közösségi médiában és weboldalakon, hogy több ügyfelet vonzzanak és növeljék az eladásokat.",
		portfolioProfessional: "Profi Autó Fotózás Cégeknek",
		portfolioProjects: "Autó Szépség Fotózások",
		servicesText: "Tudom, hogy minden autó és minden ügyfél egyedi, ezért különféle testreszabott autófotózási szolgáltatásokat kínálok, hogy megfeleljek az igényeinek. Legyen szó művészi szépségfotókról, profi képekről egy használt autó eladásához, vagy profi autó fotókról egy márka vagy autókereskedés számára, szívesen segítek. Az a célom, hogy lenyűgöző vizuális anyagokat készítsek, amelyek megragadják autóid lényegét és értékét, bármilyen célra is legyen szükséged rájuk.",
		service1Title: "Autó Szépség Fotózás",
		service1Tagline: "Kiváló minőségű, művészi autófotók, tökéletesek rajongóknak és gyűjtőknek.",
		service1Text: "A szépség fotózások célja, hogy autódat a lehető legjobb fényben mutassam be. Ezek a fotók tökéletesek az autórajongók és gyűjtők számára, akik szeretnék kiemelni járművük egyedi szépségét. Nagy figyelmet fordítok a részletekre, megörökítve az elegáns vonalakat, a csodás belső tereket és minden olyan elemet, amely különlegessé teszi autódat. Ezek a képek nem csupán fotók, hanem művészeti alkotások, amelyeket büszkén oszthatsz meg más autórajongókkal.",
		service2Title: "Használt Autó Fotózás",
		service2Tagline: "Egyszerű, mégis hatékony fotózás, hogy gyorsan el tudd adni használt autódat.",
		service2Text: "El szeretnéd adni használt autódat? A profi fotózás óriási különbséget jelenthet. Az a célom, hogy letisztult, kívánatos fotókat készítsek, amelyek kiemelik az autó állapotát és jellemzőit, vonzóbbá téve azt a potenciális vásárlók számára. A jó fotók segíthetnek gyorsabban és jobb áron eladni autódat. Garantálom, hogy a fotóimon az autód a lehető legjobban fog kinézni, segítve abban, hogy kitűnj a többi hirdetés közül. 8-12 fotót kapsz, amelyeket azonnal feltölthetsz a használt autós weboldalakra!",
		service3Title: "Márka- és Céges Fotózás",
		service3Tagline: "Profi képek az eladások növelésére és a modern közösségi média megjelenésre.",
		service3Text: "Az autós cégek és autókereskedések számára a kiváló minőségű fotók elengedhetetlenek a marketing és az értékesítés szempontjából. Profi fotókat készítek, amelyek hirdetésekben, weboldalakon és közösségi média platformokon használhatók. Ezek a fotók nemcsak az autókat mutatják be, hanem a vállalkozásod imidzsét és megbízhatóságát is közvetítik. Dolgozzunk együtt, hogy növelni tudjuk az üzleti sikereidet!",
		contactTitle: "Emeld Új Szintre Autóid Megjelenését",
		contactText: "Készen állsz, hogy autód megkapja a megérdemelt figyelmet? Legyen szó lenyűgöző szépségfotókról, hatékony használt autó képekről, vagy nagy hatású márka fotókról, itt vagyok, hogy segítsek. Vedd fel velem a kapcsolatot még ma, és megbeszéljük a részleteket. Alkossunk valami csodálatosat együtt!",
		contactButton: "Készítsünk Autós Fotókat!",
	},
};