module.exports = {
	imNotPhotogenic: {
		en: {
			name: '"I\'m Not Photogenic!"',
			slug: 'im-not-photogenic',
			pricing: {
				description: 'Quick but wholesome experience where I\'ll show you that you are indeed photogenic. Only available for first-time customers.',
				price: '40.00',
				currency: 'EUR',
				label: null,
				bulletPoints: [
					'You\'ll receive <strong>3</strong> retouched photos',
					'Up to 30 minutes of shooting',
					'1 location',
					'1 outfit',
					'Final photos delivered in 1-3 days',
				],
			},
			heroTitle: 'Being camera shy simply means no one has ever captured your true beauty in a photograph. <br><em>That changes today.</em>',
			heroTagline: 'Dive into a quick but wholesome session where we\'ll unveil your innate beauty. In just 30 minutes, I\'ll show you that you are indeed photogenic.',
			heroButtonText: 'Become Photogenic',
			experienceTitle: 'Who is this for?',
			experienceText: 'If you\'re feeling camera-shy or uncertain about your photogenic abilities, then this is the experience you\'ve been waiting for! This introductory session is designed for new customers who want to dip their toes into the world of portrait photography. It\'s ideal for individuals who have never had a professional photo session or who may feel nervous in front of the camera. <br><br><em>This experience is only available in solo format and for new customers. If you\'ve already had the pleasure of shooting with me before, I recommend upgrading to <a href="/en/experiences/the-full-experience/">The Full Experience</a> for a more immersive and personalized journey into the world of portraiture.</em>',
			experienceButtonText: 'This is for me!',
			whatsIncludedTitle: 'What You\'re Getting',
			whatsIncludedText1: 'Other than a memorable photo experience you\'ll want to tell everyone, a fresh new knowledge of simple poses to make you look your best in the future, and aching face muscles from the constant smiles? You\'re getting 3× beautifully crafted, individually edited and professionally retouched photos of yourself that you\'ll be certainly proud of.',
			whatsIncludedText2: 'Here\'s a demo gallery to get you excited!',
			whatsIncludedButtonText: 'I want to do this!',
		},
		hu: {
			name: '"Nem Vagyok Fotogén"',
			slug: 'nem-vagyok-fotogen',
			pricing: {
				description: 'Gyors de meghatározó élmény, ahol bebizonyítom, hogy igenis fotogén vagy. Csak új vendégek részére.',
				price: '10.000',
				currency: 'HUF',
				label: null,
				bulletPoints: [
					'<strong>3</strong> db retusált fotót kapsz',
					'Akár 30 perc fotózás',
					'1 helyszín',
					'1 ruha',
					'Végleges képek 1-3 napon belül',
				],
			},
			heroTitle: 'Az hogy nem vagy fotogén, azt jelenti, hogy senki nem örökítette még meg az igazi szépségedet egy fényképen. <em>Ez ma megváltozik.</em>',
			heroTagline: 'Merülj el egy gyors, de annál tartalmasabb élményben, ahol feltárjuk a benned rejlő szépséget. Mindössze 30 perc alatt megmutatom, hogy valóban fotogén vagy.',
			heroButtonText: 'Fotogénné válok',
			experienceTitle: 'Kiknek Ajánlom?',
			experienceText: 'Ha félsz a fényképezőgépektől, vagy bizonytalan vagy a fotogén képességeiddel kapcsolatban, akkor ez az az élmény, amire vártál! Ezt a bevezető élményt olyan új ügyfelek számára alakítottam ki, akik szeretnének belemerülni a portréfotózás világába. Ideális azoknak, akik még soha nem vettek részt profi fotózáson, vagy akik izgulnak a kamera előtt. <br><br><em>Ez az élmény csak egyéni formátumban és csak új ügyfelek számára érhető el. Ha már volt szerencséd korábban fotózni velem, akkor csekkold <a href="/hu/elmenyek/a-teljes-elmeny/">A Teljes Élmény</a>t, hogy még mélyebb és személyre szabottabb utazást tegyünk a portréfotózás világába.</em>',
			experienceButtonText: 'Ez nekem szól!',
			whatsIncludedTitle: 'Mit Kapsz az Élményből',
			whatsIncludedText1: 'Egy csodásan emlékezetes fotózási élményt, amit mindenkinek el akarsz majd mesélni. Frissen szerzett új tudást az egyszerű pózokról, hogy a jövőben a lehető legjobban nézz ki. Illetve zsibbadó arcizmokat az állandó mosolygástól. Mindezeken felül pedig kapsz tőlem 3 db gyönyörűen kidolgozott, egyedileg szerkesztett és professzionálisan retusált fotót magadról, amire garantáltan büszke leszel.',
			whatsIncludedText2: 'Íme egy demó galéria, hogy izgatott legyél!',
			whatsIncludedButtonText: 'Ez kell nekem!',
		},
	},
	theFullExperience: {
		en: {
			name: 'The Full Experience',
			slug: 'the-full-experience',
			pricing: {
				description: 'Dive into a world of fun and laughter with my signature portrait experience. We walk, we talk, we create photos, and you walk away being a better version of yourself.',
				price: '100.00',
				currency: 'EUR',
				label: 'Initial Investment',
				bulletPoints: [
					'You\'ll receive <strong>10</strong> edited and retouched photos of your choice',
					'Up to 2 hours of shooting',
					'Up to 2 locations',
					'Up to 2 outfits',
					'Final photos delivered in 1-5 days',
					'I\'ll gift you my favorite photo of the day, edited and retouched',
					'Additional photo selection from 5.00 EUR each with personalized discounts when choosing lots of photos',
				],
			},
			heroTitle: 'The experience everyone talks about: A comprehensive photo walk with plenty of time, variety, and fun',
			heroTagline: 'Join me for a fun and relaxed photo session where we\'ll laugh, explore, and capture your true beauty. You\'ll walk away feeling amazing and looking your best.',
			heroButtonText: 'I want to feel amazing',
			experienceTitle: 'Who is this for?',
			experienceText: 'Are you ready for a special photo experience? The Full Experience is perfect for anyone who wants a personalized and memorable photo session. Whether you\'re new to this or have done it before, this session is all about making you feel great and look fantastic. <br><br>Ideal for individuals, couples, families, or friends, this package offers flexibility to match your style. If you\'ve already had a session with me or want a more in-depth experience, this is the right choice for you.',
			experienceButtonText: 'This is for me!',
			whatsIncludedTitle: 'What\'s Included?',
			whatsIncludedText1: 'The Full Experience gives you up to 2 hours of shooting time, letting us capture many different looks and settings. You\'ll receive 10 edited and retouched photos that you\'ll love, delivered within 1-5 days. Plus, I\'ll gift you my favorite photo of the day, beautifully edited, on the very day of our photo session.',
			whatsIncludedText2: 'We\'ll explore up to 2 locations and you can even change outfits, giving us lots of options to show off your personality. You can also choose more photos with special discounts if you want even more memories to keep.',
			whatsIncludedButtonText: 'Wow, I want this!',
		},
		hu: {
			name: 'A Teljes Élmény',
			slug: 'a-teljes-elmeny',
			pricing: {
				description: 'Gyere el egy laza hangulatú, kötetlen portréfotózásra, ahol bőven van időnk sétálni, beszélgetni és fotózni. Éld át Te is az élményt, amiről mindenki beszél!',
				price: '25.000',
				currency: 'HUF',
				label: 'Induló Ár',
				bulletPoints: [
					'<strong>10</strong> db resutált fotót kapsz, amit Te választhatsz ki',
					'Kötetlen idejű fotózás',
					'2 helyszín',
					'2 ruha',
					'Végleges képek 1-5 napon belül',
					'Még a fotózás napján Neked ajándékozok 1 db általam választott fotót szerkesztve, retusálva',
					'A 10 képen felül bármennyi fotót kérhetsz mindössze 1.000 HUF darabáron',
				],
			},
			heroTitle: '',
			heroTagline: '',
			heroButtonText: '',
			experienceTitle: '',
			experienceText: '',
			experienceButtonText: '',
			whatsIncludedTitle: '',
			whatsIncludedText1: '',
			whatsIncludedText2: '',
			whatsIncludedButtonText: '',
		},
	},
	fairytaleFantasy: {
		en: {
			name: 'Fairytale Fantasy',
			slug: 'fairytale-fantasy',
			pricing: {
				description: 'Become the protagonist of your very own fairy tale. Experience a magical transformation that will create everlasting memories and magazine-worthy photographs.',
				price: '200.00',
				currency: 'EUR',
				label: 'Initial Investment',
				bulletPoints: [
					'You\'ll receive <strong>20</strong> edited and retouched photos of your choice',
					'Up to 3 hours of shooting',
					'Up to 3 locations',
					'Final photos delivered in 1-7 days',
					'I\'ll gift you my favorite photo of the day, edited and retouched',
					'Additional photo selection from 5.00 EUR each with personalized discounts when choosing lots of photos',
					'Professional make-up services included',
					'Fancy dress custome of your choice included (optional)',
				],
			},
			heroTitle: '',
			heroTagline: '',
			heroButtonText: '',
			experienceTitle: 'Who is this for?',
			experienceText: 'Calling all dreamers and adventurers! Fairytale Fantasy is designed for those who dare to dream and desire a truly enchanting experience. Whether you\'re celebrating a special occasion or simply want to indulge in a magical transformation, this package is for you. Ideal for individuals looking to channel their inner heroine or for couples seeking a romantic escapade, Fairytale Fantasy offers a whimsical journey filled with wonder and delight. With professional makeup services and the option to don a fancy dress costume, it\'s perfect for those ready to step into the spotlight and create their own fairy tale ending.',
			experienceButtonText: 'This is for me!',
			whatsIncludedTitle: '',
			whatsIncludedText1: '',
			whatsIncludedText2: '',
			whatsIncludedButtonText: '',
		},
		hu: {
			name: 'Tündérmese Fantázia',
			slug: 'tundermese-fantazia',
			pricing: {
				description: 'Legyél a saját tündérmeséd főszereplője! Élj át velünk egy varázslatos átalakulást, ahol a profi sminkeddel és a mesebeli jelmezeddel az lehetsz, aki csak akarsz, magazinba illő fotókkal megkoronázva.',
				price: '50.000',
				currency: 'HUF',
				label: 'Induló Ár',
				bulletPoints: [
					'<strong>20</strong> db resutált fotót kapsz, amit Te választhatsz ki',
					'Kötetlen idejű fotózás',
					'3 helyszín',
					'Végleges képek 1-7 napon belül',
					'Még a fotózás napján Neked ajándékozok 1 db általam választott fotót szerkesztve, retusálva',
					'A 20 képen felül bármennyi fotót kérhetsz mindössze 1.000 HUF darabáron',
					'Az élmény tartalmaz egy általad választott, professzionális sminket',
					'Az élmény tartalmazza egy általad választott jelmez bérlését is (opcionális)',
				],
			},
			heroTitle: '',
			heroTagline: '',
			heroButtonText: '',
			experienceTitle: '',
			experienceText: '',
			experienceButtonText: '',
			whatsIncludedTitle: '',
			whatsIncludedText1: '',
			whatsIncludedText2: '',
			whatsIncludedButtonText: '',
		},
	},
}
