module.exports = {
	photogenicDiscovery: {
		en: {
			name: "Photogenic Discovery",
			slug: "photogenic-discovery",
			pricing: {
				description: "Ideal for those new to portrait photography, this solo session helps you discover your photogenic side with ease and confidence.",
				price: "40.00",
				currency: "EUR",
				includes: "3 photos",
				format: "Solo only",
				duration: "30 minutes",
				locations: "1",
				outfits: "1",
				label: null,
				bulletPoints: [
					"You'll receive <strong>3 photos</strong>, professionally edited and retouched",
					"Up to 30 minutes of shooting",
					"1 location, 1 outfit",
					"Final photos delivered in 24 hours",
				],
			},
			heroTitle: "It's totally normal to feel camera shy. It just means that nobody has ever captured your true beauty in a photograph. <em>But that changes today!</em>",
			heroTagline: "Dive into a quick but impactful session where we'll unveil your innate beauty. In just 30 minutes, I'll show you that you are indeed photogenic.",
			heroButton: "Become Photogenic",
			experienceTitle: "Who is this for?",
			experienceText: "If you're feeling camera-shy or uncertain about your photogenic abilities, this is the experience you've been waiting for! I'm here to help you feel at ease and show you how to capture the perfect shot. This introductory session is perfect for those who want to dip their toes into the wonderful world of portrait photography! <br><br>This is perfect for anyone who's never had a professional photo session or who might feel a little nervous in front of the camera. If you're looking to feel more confident or just want to see yourself in a new light, this session is perfect for you! <br><br><em>This experience is only available in solo format.</em>",
			experienceButton: "This is for me!",
			whatsIncludedTitle: "What You're Getting",
			whatsIncludedBulletPoints: [
				"<strong>Solo Format:</strong> This experience is all about you, and I can't wait to help you discover your true photogenic power.",
				"<strong>30 Minutes of Shooting Time:</strong> We'll get you set up in no time and show you how to capture your best angles!",
				"<strong>1 Location, 1 Outfit:</strong> We'll choose a single location and outfit that we think will best represent you, and we can't wait to see what you choose!",
				"<strong>3 Professionally Edited and Retouched Photos:</strong> You'll receive three beautiful photos, hand-picked just for you, that highlight the best features you have to offer.",
				"<strong>Fast Turnaround:</strong> Receive your final 3 photos in under 24 hours.",
			],
			whatsIncludedSubtitle: "Here's a demo gallery to get you excited!",
			whatsIncludedButton: "Perfect, Let's Start",
			whyTitle: "Why Choose This Experience?",
			why1Title: "Boost Your Confidence",
			why1Text: "If you're looking for a little extra confidence or want to conquer your camera shyness, this is the perfect session for you!",
			why2Title: "Quick and Effective",
			why2Text: "In just 30 minutes, you can easily fit this into your day. And you'll be amazed at the results!",
			why3Title: "Personalized Attention",
			why3Text: "The solo format is perfect for getting all the attention you need to feel comfortable and look your best.",
			why4Title: "High-Quality Results",
			why4Text: "The three professionally edited photos you'll receive are curated to showcase your best self, offering a glimpse into your photogenic potential.",
			whyButton: "I Want to Do This",
			ctaTitle: "Ready to Discover Your Photogenic Side?",
			ctaText: "I truly believe that everyone is photogenic, no matter their gender, complexion, or size. I'm so excited to help you see your beauty in a whole new light! Book your Photogenic Discovery Session today to take the first step towards seeing yourself as you've never seen yourself before.",
		},
		hu: {
			name: "Fotogén Felfedezés",
			slug: "fotogen-felfedezes",
			pricing: {
				description: "Gyors de meghatározó élmény, ahol bebizonyítom, hogy igenis fotogén vagy. Csak új vendégek részére.",
				price: "10.000",
				currency: "HUF",
				includes: "3 fotó",
				format: "Egyéni",
				duration: "30 perc",
				locations: "1",
				outfits: "1",
				label: null,
				bulletPoints: [
					"<strong>3 db</strong> retusált fotót kapsz",
					"Akár 30 perc fotózás",
					"1 helyszín, 1 ruha",
					"Végleges képek 24 órán belül",
				],
			},
			heroTitle: "",
			heroTagline: "",
			heroButton: "",
			experienceTitle: "",
			experienceText: "",
			experienceButton: "",
			whatsIncludedTitle: "",
			whatsIncludedBulletPoints: [
				"",
			],
			whatsIncludedSubtitle: "",
			whatsIncludedButton: "",
			whyTitle: "",
			why1Title: "",
			why1Text: "",
			why2Title: "",
			why2Text: "",
			why3Title: "",
			why3Text: "",
			why4Title: "",
			why4Text: "",
			whyButton: "",
			ctaTitle: "",
			ctaText: "",
		},
	},
	signatureExperience: {
		en: {
			name: "Signature Experience",
			slug: "signature-experience",
			pricing: {
				description: "The most popular option, offering a personalized and memorable session for individuals, couples, families, and even pets.",
				price: "100.00",
				currency: "EUR",
				includes: "10+1 photos",
				format: "Any",
				duration: "2 hours",
				locations: "2",
				outfits: "2",
				bulletPoints: [
					"You'll receive <strong>10 photos of your choice</strong>, professionally edited and retouched + 1 photo gifted on the day of the shoot",
					"Additional photo selection from 5.00 EUR each with personalized discounts when choosing lots of photos",
					"Online consultation to customize your session to your preference",
					"Couples, families, hobbies and pets are welcome!",
					"Up to 2 hours of shooting",
					"Up to 2 locations and 2 outfits",
					"Final photos delivered in 1-3 days",
				],
			},
			heroTitle: "<em>The experience everyone talks about:</em> An easy-going, relaxed photo walk with plenty of time, variety and fun&hellip; and great photos along the way!",
			heroTagline: "Come along for a lovely, no-stress photo session where we'll have fun, explore, and capture your true beauty. You'll leave feeling absolutely amazing and looking your absolute best!",
			heroButton: "I want to feel amazing",
			experienceTitle: "Who is this for?",
			experienceText: "If you're looking for a truly personalized and truly memorable photo session, the Signature Experience is perfect for you! It doesn't matter if you're new to this or have done it before, this session is all about making you feel great and look fantastic! <br><br>This package is perfect for you and your loved ones, including pets! Whatever style you're looking for, we've got you covered. If you've already had the pleasure of a session with me or are looking for something a little more in-depth, this is the perfect choice for you!",
			experienceButton: "This is for me!",
			whatsIncludedTitle: "What You're Getting",
			whatsIncludedBulletPoints: [
				"<strong>Flexible Format:</strong> This is a great option for all kinds of portraits, from solo shots to couples, families, friends, and even pets!",
				"<strong>Unlimited Shooting Time:</strong> Typically lasting up to two hours, there's plenty of time for a variety of shots!",
				"<strong>2 Outfits and 2 Locations:</strong> You can change outfits and explore different locations to create a beautiful, diverse photo gallery just for you!",
				"<strong>10 Professionally Edited and Retouched Photos:</strong> You get to choose your favorite 10 photos, and I'll also gift you my favorite photo from the day on the day of the shoot!",
				"<strong>Additional Photos:</strong> For just 5 EUR each, you can purchase additional photos. And if you buy more, you'll save even more!",
				"<strong>Fast Turnaround:</strong> Your final photos will be ready to view and share within 3 days.",
			],
			whatsIncludedSubtitle: "Here's a few of my greatest portraits to get you excited!",
			whatsIncludedButton: "Wow, I want this!",
			whyTitle: "Why Choose This Experience?",
			why1Title: "Personalized and Flexible",
			why1Text: "Whether you're looking for a solo shoot, a couple's session, family portraits, or even including your furry friends, we've got you covered.",
			why2Title: "Ample Time and Variety",
			why2Text: "You'll have plenty of time to capture all the moments you want with up to 2 hours of shooting time, multiple outfits, and locations!",
			why3Title: "High-Quality Results",
			why3Text: "Receive 10 professionally edited photos with the option to add more, ensuring you get exactly what you want.",
			why4Title: "Fast and Convenient",
			why4Text: "Enjoy the luxury of receiving your final photos within 72 hours, along with a special photo gift on the day of the shoot.",
			whyButton: "Can't Wait, Let's Go",
			ctaTitle: "Ready for An Unforgettable Experience?",
			ctaText: "Come join me for a fun-filled session that's sure to put a big smile on your face and leave you with gorgeous photos to treasure forever. Whether you're celebrating a special occasion or just looking to create some everlasting memories, the Signature Experience is the perfect choice for you!",
		},
		hu: {
			name: "A Megszokott Élmény",
			slug: "a-megszokott-elmeny",
			pricing: {
				description: "Gyere el egy laza hangulatú, kötetlen portréfotózásra, ahol bőven van időnk sétálni, beszélgetni és fotózni. Éld át Te is az élményt, amiről mindenki beszél!",
				price: "25.000",
				currency: "HUF",
				includes: "10+1 fotó",
				format: "Bármilyen",
				duration: "2 óra",
				locations: "2",
				outfits: "2",
				bulletPoints: [
					"",
				],
			},
			heroTitle: "",
			heroTagline: "",
			heroButton: "",
			experienceTitle: "",
			experienceText: "",
			experienceButton: "",
			whatsIncludedTitle: "",
			whatsIncludedBulletPoints: [
				"",
			],
			whatsIncludedSubtitle: "",
			whatsIncludedButton: "",
			whyTitle: "",
			why1Title: "",
			why1Text: "",
			why2Title: "",
			why2Text: "",
			why3Title: "",
			why3Text: "",
			why4Title: "",
			why4Text: "",
			whyButton: "",
			ctaTitle: "",
			ctaText: "",
		},
	},
	ultimateJourney: {
		// DeepL this :arrow-down:
		en: {
			name: "Ultimate Journey",
			slug: "ultimate-journey",
			pricing: {
				description: "The ultimate in customization, providing a unique and flexible photography adventure tailored to your vision and desires.",
				price: "200.00",
				currency: "EUR",
				includes: "20+1 photos",
				format: "Any",
				duration: "Unlimited",
				locations: "Unlimited",
				outfits: "Unlimited",
				bulletPoints: [
					"You'll receive <strong>20 photos of your choice</strong>, professionally edited and retouched + 1 photo gifted on the day of the shoot",
					"Additional photo selection from 5.00 EUR each with personalized discounts when choosing lots of photos",
					"Customizable shooting times, including unique locations and extreme times of day (e.g., sunrise or night)",
					"Personal consultation to tailor the session to your vision",
					"Option to include professional makeup and themed outfits",
					"Complimentary carpool services for multiple locations",
					"Priority booking for seasonal or special events",
					"Unlimited time and locations",
					"Final photos delivered in 1-5 days",
				],
			},
			heroTitle: "Ever Dreamed of Being the Star of a Fairy Tale? <em>Now's Your Chance.</em>",
			heroTagline: "Join me for a limitless, customizable photo experience where your imagination is the only boundary. Whether it's capturing the serene beauty of a sunrise, the vibrant colors of a night shoot, or transforming into a character of your choice, the Ultimate Journey is your gateway to unforgettable portraits.",
			heroButton: "Once Upon a Time&hellip;",
			experienceTitle: "Who is this for?",
			experienceText: "Are you ready to take your photo experience to the next level? The Ultimate Journey is perfect for those who want more than just a photo session – it's for those seeking a unique, personalized adventure. Ideal for individuals, couples, families, or friends who crave creativity and customization, this package offers endless possibilities. Whether you're an early riser or a night owl, a lover of nature or an enthusiast of themed shoots, the Ultimate Journey is designed to bring your vision to life.",
			experienceButton: "This is for me!",
			whatsIncludedTitle: "What You're Getting",
			whatsIncludedBulletPoints: [
				"<strong>Unlimited Shooting Time:</strong> Enjoy a flexible schedule tailored to your needs, ensuring you get the perfect shots.",
				"<strong>20 Professionally Edited and Retouched Photos:</strong> Choose your favorite 20 photos, with the option to purchase more at a discounted rate.",
				"<strong>Unlimited Outfits and Locations:</strong> Change outfits and explore various locations to create a diverse and dynamic photo gallery.",
				"<strong>Themed and Special Location Shoots:</strong> From light painting at night to sunrise sessions and extravagant outfits, the possibilities are endless.",
				"<strong>Personal Consultation:</strong> Detailed planning and consultation before the shoot to tailor the session to your vision.",
				"<strong>Complimentary Carpool Services:</strong> Convenient transportation between multiple locations.",
				"<strong>Priority Booking:</strong> Secure your session during peak times or special events.",
				"<strong>Expedited Photo Editing:</strong> Option to expedite editing for an additional fee.",
				"<strong>Fast Turnaround:</strong> Receive your final photos within 1-5 days.",
			],
			whatsIncludedSubtitle: "Here's a few of my all-time favorite projects to get you excited!",
			whatsIncludedButton: "Ready to Live my Fairytale",
			whyTitle: "Why Choose This Experience?",
			why1Title: "Limitless Creativity",
			why1Text: "The freedom to explore any theme, location, or outfit ensures a unique and personalized experience.",
			why2Title: "Comprehensive Planning",
			why2Text: "Personal consultations and priority booking make the entire process seamless and tailored to your needs.",
			why3Title: "High-Quality and Fast Results",
			why3Text: "Receive 20 expertly edited photos quickly, with options for expedited editing.",
			why4Title: "Unique Opportunities",
			why4Text: "Capture stunning images with special techniques like light painting, sunrise sessions, and extravagant themes.",
			whyButton: "Ready for My Adventure!",
			ctaTitle: "Ready to Embark on Your Ultimate Journey?",
			ctaText: "The Ultimate Journey is designed for those who want to push the boundaries of traditional photography and explore new creative horizons. Whether it's a themed shoot, a special location, or a unique time of day, I'm here to make your vision come to life.",
		},
		hu: {
			name: "A Te Ízlésed Szerint",
			slug: "a-te-izlesed-szerint",
			pricing: {
				description: "",
				price: "50.000",
				currency: "HUF",
				includes: "20+1 fotó",
				format: "Bármilyen",
				duration: "Korlátlan",
				locations: "Korlátlan",
				outfits: "Korlátlan",
				bulletPoints: [
					"",
				],
			},
			heroTitle: "",
			heroTagline: "",
			heroButton: "",
			experienceTitle: "",
			experienceText: "",
			experienceButton: "",
			whatsIncludedTitle: "",
			whatsIncludedBulletPoints: [
				"",
			],
			whatsIncludedSubtitle: "",
			whatsIncludedButton: "",
			whyTitle: "",
			why1Title: "",
			why1Text: "",
			why2Title: "",
			why2Text: "",
			why3Title: "",
			why3Text: "",
			why4Title: "",
			why4Text: "",
			whyButton: "",
			ctaTitle: "",
			ctaText: "",
		},
	},
}
