module.exports = {
	photogenicDiscovery: {
		en: {
			name: 'Photogenic Discovery',
			slug: 'photogenic-discovery',
			pricing: {
				description: 'Ideal for those new to portrait photography, this solo session helps you discover your photogenic side with ease and confidence.',
				price: '40.00',
				currency: 'EUR',
				label: null,
				bulletPoints: [
					'You\'ll receive <strong>3 photos</strong>, professionally edited and retouched',
					'Up to 30 minutes of shooting',
					'1 location, 1 outfit',
					'Final photos delivered in 24 hours',
				],
			},
			heroTitle: 'Being camera shy simply means no one has ever captured your true beauty in a photograph. <em>That changes today.</em>',
			heroTagline: 'Dive into a quick but wholesome session where we\'ll unveil your innate beauty. In just 30 minutes, I\'ll show you that you are indeed photogenic.',
			heroButtonText: 'Become Photogenic',
			experienceTitle: 'Who is this for?',
			experienceText: 'If you\'re feeling camera-shy or uncertain about your photogenic abilities, then this is the experience you\'ve been waiting for! This introductory session is designed for new customers who want to dip their toes into the world of portrait photography. It\'s ideal for individuals who have never had a professional photo session or who may feel nervous in front of the camera. <br><br><em>This experience is only available in solo format and for new customers. If you\'ve already had the pleasure of shooting with me before, I recommend upgrading to <a href="/en/experiences/the-full-experience/">The Full Experience</a> for a more immersive and personalized journey into the world of portraiture.</em>',
			experienceButtonText: 'This is for me!',
			whatsIncludedTitle: 'What You\'re Getting',
			whatsIncludedText1: 'Other than a memorable photo experience you\'ll want to tell everyone, a fresh new knowledge of simple poses to make you look your best in the future, and aching face muscles from the constant smiles? You\'re getting 3× beautifully crafted, individually edited and professionally retouched photos of yourself that you\'ll be certainly proud of.',
			whatsIncludedText2: 'Here\'s a demo gallery to get you excited!',
			whatsIncludedButtonText: 'I want to do this!',
		},
		hu: {
			name: 'Fotogén Felfedezés',
			slug: 'fotogen-felfedezes',
			pricing: {
				description: 'Gyors de meghatározó élmény, ahol bebizonyítom, hogy igenis fotogén vagy. Csak új vendégek részére.',
				price: '10.000',
				currency: 'HUF',
				label: null,
				bulletPoints: [
					'<strong>3 db</strong> retusált fotót kapsz',
					'Akár 30 perc fotózás',
					'1 helyszín, 1 ruha',
					'Végleges képek 24 órán belül',
				],
			},
			heroTitle: 'Az hogy nem vagy fotogén, azt jelenti, hogy senki nem örökítette még meg az igazi szépségedet egy fényképen. <em>Ez ma megváltozik.</em>',
			heroTagline: 'Merülj el egy gyors, de annál tartalmasabb élményben, ahol feltárjuk a benned rejlő szépséget. Mindössze 30 perc alatt megmutatom, hogy valóban fotogén vagy.',
			heroButtonText: 'Fotogénné válok',
			experienceTitle: 'Kiknek Ajánlom?',
			experienceText: 'Ha félsz a fényképezőgépektől, vagy bizonytalan vagy a fotogén képességeiddel kapcsolatban, akkor ez az az élmény, amire vártál! Ezt a bevezető élményt olyan új ügyfelek számára alakítottam ki, akik szeretnének belemerülni a portréfotózás világába. Ideális azoknak, akik még soha nem vettek részt profi fotózáson, vagy akik izgulnak a kamera előtt. <br><br><em>Ez az élmény csak egyéni formátumban és csak új ügyfelek számára érhető el. Ha már volt szerencséd korábban fotózni velem, akkor csekkold <a href="/hu/elmenyek/a-teljes-elmeny/">A Teljes Élmény</a>t, hogy még mélyebb és személyre szabottabb utazást tegyünk a portréfotózás világába.</em>',
			experienceButtonText: 'Ez nekem szól!',
			whatsIncludedTitle: 'Mit Kapsz az Élményből',
			whatsIncludedText1: 'Egy csodásan emlékezetes fotózási élményt, amit mindenkinek el akarsz majd mesélni. Frissen szerzett új tudást az egyszerű pózokról, hogy a jövőben a lehető legjobban nézz ki. Illetve zsibbadó arcizmokat az állandó mosolygástól. Mindezeken felül pedig kapsz tőlem 3 db gyönyörűen kidolgozott, egyedileg szerkesztett és professzionálisan retusált fotót magadról, amire garantáltan büszke leszel.',
			whatsIncludedText2: 'Íme egy demó galéria, hogy izgatott legyél!',
			whatsIncludedButtonText: 'Ez kell nekem!',
		},
	},
	signatureExperience: {
		en: {
			name: 'Signature Experience',
			slug: 'signature-experience',
			pricing: {
				description: 'The most popular option, offering a personalized and memorable session for individuals, couples, families, and even pets.',
				price: '100.00',
				currency: 'EUR',
				label: 'Initial Investment',
				bulletPoints: [
					'You\'ll receive <strong>10 photos of your choice</strong>, professionally edited and retouched + 1 photo gifted on the day of the shoot',
					'Additional photo selection from 5.00 EUR each with personalized discounts when choosing lots of photos',
					'Online consultation to customize your session to your preference',
					'Couples, families, hobbies and pets are welcome!',
					'Up to 2 hours of shooting',
					'Up to 2 locations and 2 outfits',
					'Final photos delivered in 1-3 days',
				],
			},
			heroTitle: '<em>The experience everyone talks about:</em> A comprehensive photo walk with plenty of time, variety, and fun',
			heroTagline: 'Join me for a fun and relaxed photo session where we\'ll laugh, explore, and capture your true beauty. You\'ll walk away feeling amazing and looking your best.',
			heroButtonText: 'I want to feel amazing',
			experienceTitle: 'Who is this for?',
			experienceText: 'Are you ready for a special photo experience? The Full Experience is perfect for anyone who wants a personalized and memorable photo session. Whether you\'re new to this or have done it before, this session is all about making you feel great and look fantastic. <br><br>Ideal for individuals, couples, families, or friends, this package offers flexibility to match your style. If you\'ve already had a session with me or want a more in-depth experience, this is the right choice for you.',
			experienceButtonText: 'This is for me!',
			whatsIncludedTitle: 'What\'s Included?',
			whatsIncludedText1: 'The Full Experience gives you up to 2 hours of shooting time, letting us capture many different looks and settings. You\'ll receive 10 edited and retouched photos that you\'ll love, delivered within 1-5 days. Plus, I\'ll gift you my favorite photo of the day, beautifully edited, on the very day of our photo session.',
			whatsIncludedText2: 'We\'ll explore up to 2 locations and you can even change outfits, giving us lots of options to show off your personality. You can also choose more photos with special discounts if you want even more memories to keep.',
			whatsIncludedButtonText: 'Wow, I want this!',
		},
		hu: {
			name: 'A Megszokott Élmény',
			slug: 'a-megszokott-elmeny',
			pricing: {
				description: 'Gyere el egy laza hangulatú, kötetlen portréfotózásra, ahol bőven van időnk sétálni, beszélgetni és fotózni. Éld át Te is az élményt, amiről mindenki beszél!',
				price: '25.000',
				currency: 'HUF',
				label: 'Induló Ár',
				bulletPoints: [
					'<strong>10 db</strong> resutált fotót kapsz, amit Te választhatsz ki + 1 ajándék fénykép még a fotózás napján',
					'További képek mindössze 1.000 HUF darabáron',
					'Akár 2 óra fotózás',
					'2 helyszín, 2 ruha',
					'Végleges képek 1-3 napon belül',
				],
			},
			heroTitle: '',
			heroTagline: '',
			heroButtonText: '',
			experienceTitle: '',
			experienceText: '',
			experienceButtonText: '',
			whatsIncludedTitle: '',
			whatsIncludedText1: '',
			whatsIncludedText2: '',
			whatsIncludedButtonText: '',
		},
	},
	ultimateJourney: {
		en: {
			name: 'Ultimate Journey',
			slug: 'ultimate-journey',
			pricing: {
				description: 'The ultimate in customization, providing a unique and flexible photography adventure tailored to your vision and desires.',
				price: '200.00',
				currency: 'EUR',
				label: 'Initial Investment',
				bulletPoints: [
					'You\'ll receive <strong>20 photos of your choice</strong>, professionally edited and retouched + 1 photo gifted on the day of the shoot',
					'Additional photo selection from 5.00 EUR each with personalized discounts when choosing lots of photos',
					'Customizable shooting times, including unique locations and extreme times of day (e.g., sunrise or night)',
					'Personal consultation to tailor the session to your vision',
					'Option to include professional makeup and themed outfits',
					'Complimentary carpool services for multiple locations',
					'Priority booking for seasonal or special events',
					'Unlimited time and locations',
					'Final photos delivered in 1-5 days',
				],
			},
			heroTitle: 'Ever Dreamed of Being the Star of a Fairy Tale? <em>Now\'s Your Chance.</em>',
			heroTagline: 'Join me for a magical photo session where we’ll bring your fairy tale to life with personalized touches. Enjoy professional makeup and multiple outfit changes to create your dream photos.',
			heroButtonText: 'Once Upon a Time&hellip;',
			experienceTitle: 'Who is this for?',
			experienceText: 'Calling all dreamers and adventurers! Fairytale Fantasy is designed for those who dare to dream and desire a truly enchanting experience. Whether you\'re celebrating a special occasion or simply want to indulge in a magical transformation, this package is for you. Ideal for individuals looking to channel their inner heroine or for couples seeking a romantic escapade, Fairytale Fantasy offers a whimsical journey filled with wonder and delight. With professional makeup services and the option to don a fancy dress costume, it\'s perfect for those ready to step into the spotlight and create their own fairy tale ending.',
			experienceButtonText: 'This is for me!',
			whatsIncludedTitle: 'What\'s Included?',
			whatsIncludedText1: 'The Fairytale Fantasy experience gives you up to 3 hours of shooting time, allowing us to explore multiple enchanting locations and looks. You\'ll receive 20 edited and professionally retouched photos that will make you feel like royalty, delivered within 1-7 days. Plus, I\'ll gift you my favorite photo of the day, beautifully edited.',
			whatsIncludedText2: 'We\'ll visit up to 3 different locations and you can choose from a variety of costumes, giving us lots of options to create your fairy tale. Professional makeup services are included to complete your transformation. You can also choose more photos with special discounts if you want even more magical memories to keep.',
			whatsIncludedButtonText: 'Ready to Live my Fairytale',
		},
		hu: {
			name: 'A Te Ízlésed Szerint',
			slug: 'a-te-izlesed-szerint',
			pricing: {
				description: 'Legyél a saját tündérmeséd főszereplője! Élj át velünk egy varázslatos átalakulást, ahol a profi sminkeddel és a mesebeli jelmezeddel az lehetsz, aki csak akarsz, magazinba illő fotókkal megkoronázva.',
				price: '50.000',
				currency: 'HUF',
				label: 'Induló Ár',
				bulletPoints: [
					'<strong>20 db</strong> resutált fotót kapsz, amit Te választhatsz ki + 1 ajándék fénykép még a fotózás napján',
					'További képek mindössze 1.000 HUF darabáron',
					'Kötetlen idejű fotózás',
					'Bármennyi helyszín',
					'Végleges képek 1-5 napon belül',
					'Még a fotózás napján Neked ajándékozok 1 db általam választott fotót szerkesztve, retusálva',
					'Az élmény tartalmaz egy általad választott, professzionális sminket',
					'Az élmény tartalmazza egy általad választott jelmez bérlését is (opcionális)',
				],
			},
			heroTitle: '',
			heroTagline: '',
			heroButtonText: '',
			experienceTitle: '',
			experienceText: '',
			experienceButtonText: '',
			whatsIncludedTitle: '',
			whatsIncludedText1: '',
			whatsIncludedText2: '',
			whatsIncludedButtonText: '',
		},
	},
}
