module.exports = [
	{
		name: "Abdallah",
		filename: "abdallah",
		category: "male",
		date: "2023.02.06.",
		priority: "",
	},
	{
		name: "Ádám",
		filename: "adam",
		category: "male",
		date: "2023.05.26.",
		priority: "",
	},
	{
		name: "Aiganysh",
		filename: "aiganysh",
		category: "female",
		date: "2024.03.19.",
		priority: "",
	},
	{
		name: "Aisouda",
		filename: "aisouda",
		category: "female",
		date: "2023.12.09.",
		priority: "",
	},
	{
		name: "Alíz",
		filename: "aliz",
		category: "female",
		date: "2024.10.29.",
		priority: "",
	},
	{
		name: "Amanda",
		filename: "amanda",
		category: "female",
		date: "2024.01.19.",
		priority: "",
	},
	{
		name: "Andi",
		filename: "andi",
		category: "female",
		date: "2023.11.08.",
		priority: "",
	},
	{
		name: "Anna",
		filename: "anna-2",
		category: "female",
		date: "2023.11.22.",
		priority: "",
	},
	{
		name: "Anna",
		filename: "anna-3",
		category: "female",
		date: "2023.12.12.",
		priority: "",
	},
	{
		name: "Anna",
		filename: "anna-4",
		category: "female",
		date: "2023.07.16.",
		priority: "",
	},
	{
		name: "Anna & Patrik",
		filename: "anna-patrik",
		category: "couple",
		date: "2025.02.09.",
		priority: "",
	},
	{
		name: "Anna",
		filename: "anna",
		category: "female",
		date: "2022.10.25.",
		priority: "",
	},
	{
		name: "Balázs",
		filename: "balazs",
		category: "male",
		date: "2022.09.17.",
		priority: "",
	},
	{
		name: "Bea",
		filename: "bea",
		category: "female",
		date: "2024.07.04.",
		priority: "",
	},
	{
		name: "Bence",
		filename: "bence",
		category: "male",
		date: "2024.07.25.",
		priority: "",
	},
	{
		name: "Betti & Laci",
		filename: "betti-laci",
		category: "couple",
		date: "2023.11.26.",
		priority: "",
	},
	{
		name: "Bia",
		filename: "bia",
		category: "female",
		date: "2024.08.09.",
		priority: "",
	},
	{
		name: "Blanka",
		filename: "blanka",
		category: "female",
		date: "2023.11.18.",
		priority: "",
	},
	{
		name: "Boróka",
		filename: "boroka",
		category: "female",
		date: "2024.08.28.",
		priority: "",
	},
	{
		name: "Burcu & Sebastian",
		filename: "burcu-sebastian",
		category: "couple",
		date: "2023.09.22.",
		priority: "",
	},
	{
		name: "Csenge",
		filename: "csenge",
		category: "female",
		date: "2023.05.21.",
		priority: "",
	},
	{
		name: "Dávid",
		filename: "david",
		category: "male",
		date: "2024.10.29.",
		priority: "",
	},
	{
		name: "Detti & Dani",
		filename: "detti-dani",
		category: "couple",
		date: "2023.05.28.",
		priority: "",
	},
	{
		name: "Dóri & Jonatán & Adél",
		filename: "dori-jonatan-adel",
		category: "couple",
		date: "2023.09.01.",
		priority: "",
	},
	{
		name: "Dóri & Laci",
		filename: "dori-laci",
		category: "couple",
		date: "2023.12.16.",
		priority: "",
	},
	{
		name: "Dóri",
		filename: "dori",
		category: "female",
		date: "2024.04.30.",
		priority: "",
	},
	{
		name: "Dzsenifer",
		filename: "dzsenifer",
		category: "female",
		date: "2025.01.05.",
		priority: "",
	},
	{
		name: "Eperke",
		filename: "eperke",
		category: "female",
		date: "2022.09.13.",
		priority: "",
	},
	{
		name: "Erwin",
		filename: "erwin",
		category: "male",
		date: "2024.12.08.",
		priority: "",
	},
	{
		name: "Eszter",
		filename: "eszter-2",
		category: "female",
		date: "2022.09.01.",
		priority: "",
	},
	{
		name: "Eszter",
		filename: "eszter-3",
		category: "female",
		date: "2023.10.06.",
		priority: "",
	},
	{
		name: "Eszter",
		filename: "eszter-4",
		category: "female",
		date: "2024.04.25.",
		priority: "",
	},
	{
		name: "Eszter",
		filename: "eszter",
		category: "female",
		date: "2024.05.26.",
		priority: "",
	},
	{
		name: "Évi",
		filename: "evi",
		category: "female",
		date: "2024.06.08.",
		priority: "",
	},
	{
		name: "Fanni",
		filename: "fanni-2",
		category: "female",
		date: "2024.07.29.",
		priority: "",
	},
	{
		name: "Fanni",
		filename: "fanni",
		category: "female",
		date: "2025.01.08.",
		priority: "",
	},
	{
		name: "Feri",
		filename: "feri",
		category: "male",
		date: "2023.07.10.",
		priority: "",
	},
	{
		name: "Fruzsi",
		filename: "fruzsi",
		category: "female",
		date: "2023.11.03.",
		priority: "",
	},
	{
		name: "Gabi",
		filename: "gabi-2",
		category: "female",
		date: "2023.03.04.",
		priority: "",
	},
	{
		name: "Gabi",
		filename: "gabi",
		category: "female",
		date: "2024.05.17.",
		priority: "",
	},
	{
		name: "Gábor",
		filename: "gabor-2",
		category: "male",
		date: "2024.05.25.",
		priority: "",
	},
	{
		name: "Gábor",
		filename: "gabor",
		category: "male",
		date: "2023.06.28.",
		priority: "",
	},
	{
		name: "Gerda",
		filename: "gerda",
		category: "female",
		date: "2025.01.26.",
		priority: "",
	},
	{
		name: "Gergely",
		filename: "gergely",
		category: "male",
		date: "2024.10.14.",
		priority: "",
	},
	{
		name: "Gréti",
		filename: "greti",
		category: "female",
		date: "2023.08.14.",
		priority: "",
	},
	{
		name: "Gyuri",
		filename: "gyuri",
		category: "male",
		date: "2023.06.14.",
		priority: "",
	},
	{
		name: "Iulia & Radu",
		filename: "iulia-radu",
		category: "couple",
		date: "2023.06.30.",
		priority: "",
	},
	{
		name: "Jázmin & Beni",
		filename: "jazmin-beni",
		category: "couple",
		date: "2023.10.08.",
		priority: "",
	},
	{
		name: "Jázmin",
		filename: "jazmin",
		category: "female",
		date: "2024.08.12.",
		priority: "",
	},
	{
		name: "karen",
		filename: "karen",
		category: "female",
		date: "2024.05.30.",
		priority: "",
	},
	{
		name: "Karina",
		filename: "karina",
		category: "female",
		date: "2024.10.03.",
		priority: "",
	},
	{
		name: "Kata",
		filename: "kata",
		category: "female",
		date: "2025.01.19.",
		priority: "",
	},
	{
		name: "Katinka",
		filename: "katinka",
		category: "female",
		date: "2024.10.20.",
		priority: "",
	},
	{
		name: "Katja",
		filename: "katja",
		category: "female",
		date: "2023.01.23.",
		priority: "",
	},
	{
		name: "Kincső",
		filename: "kincso",
		category: "female",
		date: "2023.02.12.",
		priority: "",
	},
	{
		name: "Kitti",
		filename: "kitti",
		category: "female",
		date: "2024.09.26.",
		priority: "",
	},
	{
		name: "Klemi & Ádám",
		filename: "klemi-adam",
		category: "couple",
		date: "2023.10.20.",
		priority: "",
	},
	{
		name: "Krisztián",
		filename: "krisztian",
		category: "male",
		date: "2023.09.01.",
		priority: "",
	},
	{
		name: "Kseniia & Nicolo",
		filename: "kseniia-nicolo",
		category: "couple",
		date: "2024.10.04.",
		priority: "",
	},
	{
		name: "Laci",
		filename: "laci-2",
		category: "male",
		date: "2024.09.22.",
		priority: "",
	},
	{
		name: "Laci",
		filename: "laci",
		category: "male",
		date: "2024.09.22.",
		priority: "",
	},
	{
		name: "LaRae",
		filename: "larae",
		category: "female",
		date: "2023.07.03.",
		priority: "",
	},
	{
		name: "Laura",
		filename: "laura-2",
		category: "female",
		date: "2023.06.29.",
		priority: "",
	},
	{
		name: "Laura",
		filename: "laura",
		category: "female",
		date: "2024.03.26.",
		priority: "",
	},
	{
		name: "Lili",
		filename: "lili",
		category: "female",
		date: "2024.08.13.",
		priority: "",
	},
	{
		name: "Lilla & Csabi & Moha",
		filename: "lilla-csabi-moha",
		category: "couple",
		date: "2022.10.09.",
		priority: "",
	},
	{
		name: "Linda & Erwin",
		filename: "linda-erwin",
		category: "couple",
		date: "2024.12.08.",
		priority: "",
	},
	{
		name: "Marcsi",
		filename: "marcsi",
		category: "female",
		date: "2024.06.13.",
		priority: "",
	},
	{
		name: "Márk",
		filename: "mark",
		category: "male",
		date: "2023.10.03.",
		priority: "",
	},
	{
		name: "Máté",
		filename: "mate",
		category: "male",
		date: "2024.04.13.",
		priority: "",
	},
	{
		name: "Merci",
		filename: "merci",
		category: "female",
		date: "2023.06.17.",
		priority: "",
	},
	{
		name: "Mira",
		filename: "mira",
		category: "female",
		date: "2023.06.23.",
		priority: "",
	},
	{
		name: "Mona",
		filename: "mona",
		category: "female",
		date: "2024.05.13.",
		priority: "",
	},
	{
		name: "Nicolas",
		filename: "nicolas",
		category: "male",
		date: "2022.12.02.",
		priority: "",
	},
	{
		name: "Nóri",
		filename: "nori",
		category: "female",
		date: "2024.03.15.",
		priority: "",
	},
	{
		name: "Orsi",
		filename: "orsi",
		category: "female",
		date: "2023.01.25.",
		priority: "",
	},
	{
		name: "Parinita & Roopesh",
		filename: "parinita-roopesh",
		category: "couple",
		date: "2024.06.17.",
		priority: "",
	},
	{
		name: "Patrick",
		filename: "patrick",
		category: "male",
		date: "2023.08.13.",
		priority: "",
	},
	{
		name: "Petra & Attila & Emili",
		filename: "petra-attila-emili",
		category: "couple",
		date: "2024.07.09.",
		priority: "",
	},
	{
		name: "Petra",
		filename: "petra",
		category: "female",
		date: "2025.01.10.",
		priority: "",
	},
	{
		name: "Polina & Nijat",
		filename: "polina-nijat",
		category: "couple",
		date: "2024.07.06.",
		priority: "",
	},
	{
		name: "Polina",
		filename: "polina",
		category: "female",
		date: "2023.05.05.",
		priority: "",
	},
	{
		name: "Rachel",
		filename: "rachel",
		category: "female",
		date: "2024.05.28.",
		priority: "",
	},
	{
		name: "Réka",
		filename: "reka-2",
		category: "female",
		date: "2023.04.21.",
		priority: "",
	},
	{
		name: "Réka",
		filename: "reka-3",
		category: "female",
		date: "2025.03.06.",
		priority: "",
	},
	{
		name: "Réka & Ádám",
		filename: "reka-adam-2",
		category: "couple",
		date: "2023.01.27.",
		priority: "",
	},
	{
		name: "Réka & Ádám",
		filename: "reka-adam",
		category: "couple",
		date: "2024.05.28.",
		priority: "",
	},
	{
		name: "Réka",
		filename: "reka",
		category: "female",
		date: "2024.05.01.",
		priority: "",
	},
	{
		name: "Renda & Bastian",
		filename: "renda-bastian",
		category: "couple",
		date: "2025.02.14.",
		priority: "",
	},
	{
		name: "Rikarda & Krisztián",
		filename: "rikarda-krisztian",
		category: "couple",
		date: "2023.09.01.",
		priority: "",
	},
	{
		name: "Saci",
		filename: "saci",
		category: "female",
		date: "2024.09.01.",
		priority: "",
	},
	{
		name: "Sanyi",
		filename: "sanyi",
		category: "male",
		date: "2023.09.12.",
		priority: "",
	},
	{
		name: "StandOut",
		filename: "standout",
		category: "male",
		date: "2025.02.02.",
		priority: "",
	},
	{
		name: "Szilvi & Laci",
		filename: "szilvi-laci",
		category: "couple",
		date: "2024.04.06.",
		priority: "",
	},
	{
		name: "Szilvi",
		filename: "szilvi",
		category: "female",
		date: "2023.05.25.",
		priority: "",
	},
	{
		name: "Tamara",
		filename: "tamara",
		category: "female",
		date: "2022.05.26.",
		priority: "",
	},
	{
		name: "Tamás",
		filename: "tamas",
		category: "male",
		date: "2023.05.10.",
		priority: "",
	},
	{
		name: "Tatum",
		filename: "tatum",
		category: "female",
		date: "2023.07.16.",
		priority: "",
	},
	{
		name: "Tim",
		filename: "tim",
		category: "male",
		date: "2022.11.30.",
		priority: "",
	},
	{
		name: "Timi",
		filename: "timi",
		category: "female",
		date: "2025.03.04.",
		priority: "",
	},
	{
		name: "Utkarsh",
		filename: "utkarsh",
		category: "male",
		date: "2025.01.26.",
		priority: "",
	},
	{
		name: "Velva",
		filename: "velva",
		category: "female",
		date: "2023.12.05.",
		priority: "",
	},
	{
		name: "Veronika & Szabolcs",
		filename: "veronika-szabolcs",
		category: "couple",
		date: "2024.08.16.",
		priority: "",
	},
	{
		name: "Veronika",
		filename: "veronika",
		category: "female",
		date: "2024.02.17.",
		priority: "",
	},
	{
		name: "Viki & Egon & Félix",
		filename: "viki-egon-felix",
		category: "couple",
		date: "2024.10.15.",
		priority: "",
	},
	{
		name: "Viki",
		filename: "viki",
		category: "female",
		date: "2024.02.22.",
		priority: "",
	},
	{
		name: "Viktor",
		filename: "viktor",
		category: "male",
		date: "2024.09.27.",
		priority: "",
	},
	{
		name: "Virág",
		filename: "virag-2",
		category: "female",
		date: "2024.05.28.",
		priority: "",
	},
	{
		name: "Virág & Dávid",
		filename: "virag-david",
		category: "couple",
		date: "2024.10.29.",
		priority: "",
	},
	{
		name: "Virág",
		filename: "virag",
		category: "female",
		date: "2024.10.29.",
		priority: "",
	},
	{
		name: "Vivi & Norbi",
		filename: "vivi-norbi",
		category: "couple",
		date: "2024.09.07.",
		priority: "",
	},
	{
		name: "Vivi",
		filename: "vivi",
		category: "female",
		date: "2025.02.19.",
		priority: "",
	},
	{
		name: "Vivien",
		filename: "vivien",
		category: "female",
		date: "2024.06.08.",
		priority: "",
	},
	{
		name: "Willie & Alexa",
		filename: "willie-alexa",
		category: "couple",
		date: "2024.10.08.",
		priority: "",
	},
	{
		name: "Zsani",
		filename: "zsani",
		category: "female",
		date: "2024.05.24.",
		priority: "",
	},
	{
		name: "Zsófi & Benedek",
		filename: "zsofi-benedek",
		category: "couple",
		date: "2024.05.31.",
		priority: "",
	},
	{
		name: "Zsófi",
		filename: "zsofi",
		category: "female",
		date: "2024.10.19.",
		priority: "",
	},
	{
		name: "Zsuzsi & Gyuri",
		filename: "zsuzsi-gyuri",
		category: "couple",
		date: "2023.11.04.",
		priority: "",
	},
];
