module.exports = {
	url: "https://rolandszabo.photo",
	languages: [
		{
			code: "en",
			label: "English",
		},
		{
			code: "hu",
			label: "Magyar",
		},
	],
	en: {
		siteTitle: "Roland Szabó | Budapest Portrait Photographer",
		copyright: "All rights reserved.",
		backToTop: "Back to the top of the page",
		backToHomepage: "Back to the Homepage",

		headerName: "Roland Szabó",
		headerDescription: "Budapest Portrait Photographer",

		navProjects: "Projects",
		navMyWork: "Work",
		navMe: "About",
		navBlog: "My Photography Blog",
		navFemalePortraits: "Female Portrait Portfolio",
		navMalePortraits: "Male Portrait Portfolio",
		navCouplePortraits: "Couple/Family Portrait Portfolio",
		navAbout: "Introduction",
		navExperiences: "Experiences",
		navExperiencesCategory: "Portrait Photography Experiences with Roland",
		navServices: "Services",
		navServicesPortraiture: "Relaxed Portrait Photography in Budapest",
		navServicesSocialContent: "Product Photography & Social Content Creation",
		navServicesAutomotive: "Automotive Photography",
		navPhotoWalks: "Photoshoot",
		navPortraitWorks: "All Galleries",
		navContact: "Contact Me",
		navGear: "Gear I Use",
		navTestimonials: "Testimonials",
		navBudapestPhotoWalk: "Budapest Photo Walk",

		slugAbout: "about",
		slugBlog: "blog",
		slugBudapestPhotoWalk: "budapest-photo-walk",
		slugGalleries: "galleries",
		slugGalleriesPortraiture: "portraiture",
		slugGalleriesSocialContent: "social-content",
		slugGalleriesAutomotive: "automotive",
		slugFemalePortraits: "female-portraits",
		slugMalePortraits: "male-portraits",
		slugCouplePortraits: "couple-portraits",
		slugExperiences: "experiences",
		slugServices: "services",
		slugPortraitPhotography: "portrait-photo-walks",
		slugSocialPhotography: "social-media-content-creation",
		slugCarPhotography: "automotive-photography",
		slugContact: "contact",
		slugGear: "gear",
		slugTestimonials: "testimonials",

		homepageNavPortrait: "Portraiture",
		homepageNavSocial: "Social Content",
		homepageNavAutomotive: "Automotive",
		homepageMainTitle: "Capturing Real Moments, One Awkward Joke at a Time.",
		homepageRecentTitle: "Latest Portrait Work",
		homepageVisitLatest: "or see my latest work",
		homepageVisitGalleries: "or check out all of my galleries",
		homepageVisitAbout: "or get to know me better",
		homepageVisitTestimonials: "or read all of my reviews",
		homepageTestimonials: "Most Recent Reviews",

		lightboxNextPhoto: "Next Photo",
		lightboxPreviousPhoto: "Previous Photo",
		lightboxClose: "Close",

		aboutPhotoTitle: "Hey, it's me!",
		contactPhotoTitle: "How can I help you?",
		gearPhotoTitle: "I'm on fire, baby!",
		homePhotoTitle: "Visible concentration :D",

		ctaTitle: "Let's Create Your Unique Story",
		ctaText: "Whether you have a creative idea in mind or simply want to discover the magic of being authentically captured, the next chapter of your story starts here.",
		ctaButton: "Choose Your Experience",
		latestButton: "Check out my Recent Work",

		contactEmailText: "Drop me an email with your idea",
		contactEmailButton: "Write an Email",
		contactInstagramText: "Or better, DM me on Instagram",
		contactInstagramButton: "DM on Instagram",
	
		socialTagline: "Your business deserves more than smartphone photos",
		socialCtaTitle: "Ready to get started with your own brand's professional photography?",
		socialCtaDescription: "If you like the above examples and would like to work with me in telling your brand's story through my images, don't be afraid to get in touch with me!",
		socialCtaButton: "Let's work together!",

		whosBehindTitle: 'Who\'s Behind the Camera?',
		whosBehindText1: 'Great question! Hi, I\'m Roland, and I help people like you feel your best in front of the camera. I firmly believe that everyone is inherently photogenic and I\'m here to show it, one photograph at a time.',
		whosBehindText2: 'With my empathetic personality and horrible sense of humour, I\'ll create an easy-going atmosphere where you can be your true self and not be afraid of the camera. We talk a lot, we walk a lot and we laugh a lot together. We also take some photos here and there that you\'ll definitely love in the end.',
		whosBehindText3: 'You don\'t need to worry about posing, I\ll be helping you all along the way. Now, I know what you\'re thinking: I don\'t want my photos to look posed. I get it! So instead of showing you concrete poses, I\'ll actually teach you how to look your best when you\'re being photographed, so you can feel more confident the next time it comes to taking your photos.',
		whosBehindText4: 'Now, if this all makes you shiver in excitement, then here\'s your ways to contact me and get started on your photographic journey.',
		otherWaysTitle: 'Other ways I can help you',
		otherWaysLearnMore: 'Learn More',

		blogWrittenBy: "Written by",
		blogWrittenOn: "on",
		blogRolandSzabo: "Roland Szabó",

		faq: "Frequently Asked Questions",
		summaryPrice: "Price",
		summaryIncludes: "Includes",
		summaryDuration: "Duration",
		summaryFormat: "Format",
		summaryLocations: "Locations",
		summaryOutfits: "Outfits",
	},
	hu: {
		siteTitle: "Szabó Roland | Budapesti Portré Fotós",
		copyright: "Minden jog fenntartva.",
		backToTop: "Vissza az oldal tetejére",
		backToHomepage: "Vissza a Kezdőoldalra",

		headerName: "Szabó Roland",
		headerDescription: "Budapesti Portré Fotós",

		navProjects: "Projektek",
		navMyWork: "Munkáim",
		navMe: "Rólam",
		navBlog: "Fotós Blogom",
		navFemalePortraits: "Női Portré Portfólió",
		navMalePortraits: "Férfi Portré Portfólió",
		navCouplePortraits: "Páros/Családi Portré Portfólió",
		navAbout: "Bemutatkozás",
		navExperiences: "Élmények",
		navExperiencesCategory: "Portré Fotózás Élmények Rolanddal",
		navServices: "Szolgáltatások",
		navServicesPortraiture: "Portré Fotózás Budapesten",
		navServicesSocialContent: "Termékfotózás, Közösségi Tartalomgyártás",
		navServicesAutomotive: "Új- és Használtautó Fotózás",
		navPhotoWalks: "Portréfotózás",
		navPortraitWorks: "Összes Galéria",
		navContact: "Elérhetőségeim",
		navGear: "Felszerelés",
		navTestimonials: "Rólam Mondtátok",
		navBudapestPhotoWalk: "Budapest Photo Walk",

		slugAbout: "rolam",
		slugBlog: "blog",
		slugBudapestPhotoWalk: "budapest-photo-walk",
		slugGalleries: "galeriak",
		slugGalleriesPortraiture: "portre",
		slugGalleriesSocialContent: "kozossegi-tartalom",
		slugGalleriesAutomotive: "auto",
		slugFemalePortraits: "noi-portrek",
		slugMalePortraits: "ferfi-portrek",
		slugCouplePortraits: "paros-portrek",
		slugExperiences: "elmenyek",
		slugServices: "szolgaltatasok",
		slugPortraitPhotography: "portre-fotos-setak",
		slugSocialPhotography: "kozossegi-tartalom-gyartas",
		slugCarPhotography: "auto-fotozas",
		slugContact: "kapcsolat",
		slugGear: "felszereles",
		slugTestimonials: "rolam-mondtak",

		homepageNavPortrait: "Portré",
		homepageNavSocial: "Közösségi Tartalom",
		homepageNavAutomotive: "Autó",
		homepageMainTitle: "Őszinte portré fotókat készítek és borzalmas vicceket mesélek.",
		homepageRecentTitle: "Legutóbbi Munkáim",
		homepageButton: "Fotózzunk!",
		homepageVisitLatest: "vagy nézd meg a legfrissebb munkáimat",
		homepageVisitGalleries: "vagy nézd meg a galériámat",
		homepageVisitAbout: "vagy ismerj meg jobban",
		homepageVisitTestimonials: "vagy olvasd el az összes értékelésemet",
		homepageTestimonials: "Rólam Mondtátok",

		lightboxNextPhoto: "Következő Fotó",
		lightboxPreviousPhoto: "Előző Fotó",
		lightboxClose: "Bezárás",

		aboutPhotoTitle: "Halihó, ez itt én vagyok.",
		contactPhotoTitle: "Miben tudok segíteni?",
		gearPhotoTitle: "Elég forró volt a helyzet...",
		homePhotoTitle: "Ne zavarj, koncentrálok! :D",

		ctaTitle: "Készítsük el a Te Történetedet",
		ctaText: "Akár egy kreatív ötlet jár a fejedben, vagy egyszerűen csak szeretnéd felfedezni az őszinte kifejezés varázsát, a történeted következő fejezete itt kezdődik.",
		ctaButton: "Válassz Élményt",
		latestButton: "Nézd Meg a Munkáimat",

		contactEmailText: "Írj egy emailt és beszéljünk",
		contactEmailButton: "Emailt írok",
		contactInstagramText: "Vagy írj rám Instagramon, az még jobb",
		contactInstagramButton: "Írok Instán",

		socialTagline: "A vállalkozásod többet érdemel a mobiltelefonos fotóknál",
		socialCtaTitle: "Szeretnéd, hogy a Te márkádnak is végre profi képei legyenek?",
		socialCtaDescription: "Ha tetszenek a fenti képek és szeretnél a Te vállalkozásodnak is szemet gyönyörködtető képeket, keress meg bizalommal! Szeretettel dolgoznék együtt kisvállalkozókkal, hazai cégekkel és influenszerekkel, hogy olyan képeket tudjunk alkotni közösen, amik elmesélik a márkád történetét és megszólítják az embereket.",
		socialCtaButton: "Készen állok, csináljuk!",

		whosBehindTitle: 'Ki van a Kamera Mögött?',
		whosBehindText1: 'Jó kérdés! Szia, Roland vagyok, és a Hozzád hasonló, hétköznapi embereknek segítek abban, hogy ne izguljanak a kamerától. Hiszek abban, hogy mindenki önmagából eredően fotogén, és hogy mindenkiről tudok előnyös fényképet készíteni.',
		whosBehindText2: 'Empatikus személyiségemnek és borzalmas humoromnak köszönhetően olyan nyugodt légkört tudok teremteni a fotós sétáink alatt, amiben igazán Önmagad lehetsz, és nem fogsz izgulni a kamera láttán. Sokat sétálunk, sokat beszélgetünk és még többet röhögünk. Mindeközben elkattintunk pár fotót itt-ott, amiket imádni fogsz a végén.',
		whosBehindText3: 'Nem kell izgulnod a pózolástól sem, mert segíteni foglak végig. Tudom, hogy nem szeretnél "pózolt" fotókat, de aggodalomra semmi ok! Konkrét pózok mutatása helyett azt fogom megmutatni, hogy mire kell figyelned, ha fotóznak, így legközelebb már tudni fogod, hogyan fogsz a legjobban kinézni.',
		whosBehindText4: 'Ha a fentiek jól hangzanak, akkor íme néhány módja a kapcsolatteremtésnek. Alig várom, hogy halljak felőled!',
		otherWaysTitle: 'Így is Tudok Segíteni',
		otherWaysLearnMore: 'Tudj meg többet',

		blogWrittenBy: "Írta",
		blogWrittenOn: "ekkor:",
		blogRolandSzabo: "Szabó Roland",

		faq: "Gyakran Ismételt Kérdések",
		summaryPrice: "Ár",
		summaryIncludes: "Tartalmaz",
		summaryDuration: "Fotózás Időtartama",
		summaryFormat: "Formátum",
		summaryLocations: "Helyszínek",
		summaryOutfits: "Ruhák",
	},
};
