module.exports = {
	languages: [
		{
			code: "en",
			label: "English",
		},
		{
			code: "hu",
			label: "Magyar",
		},
	],
	en: {
		"siteTitle": "Roland Szabó Photography",
		"copyright": "All rights reserved.",

		"photoBy": "Photo by",
		"photoAndEditBy": "Photo and edit by",
		"peterLakinger": "Peter Lakinger",
		"csanadAlfoldi": "Csanad Alfoldi",
		"danosNemeth": "Danos Nemeth",

		"headerName": "Roland Szabó",
		"headerDescription": "Budapest-based Photographer",

		"navAbout": "About",
		"navGalleries": "Galleries",
		"navGalleriesPortraiture": "Portraiture",
		"navGalleriesSocialContent": "Social Content",
		"navGalleriesAutomotive": "Automotive",
		"navServices": "Services",
		"navServicesPortraiture": "Portrait Photo Walks",
		"navServicesSocialContent": "Social Content Creation",
		"navServicesAutomotive": "Automotive Photography",
		"navPhotoWalks": "Photo Walks",
		"navContact": "Contact",
		"navGear": "Gear",

		"slugAbout": "about",
		"slugGalleries": "galleries",
		"slugGalleriesPortraiture": "portraiture",
		"slugGalleriesSocialContent": "social-content",
		"slugGalleriesAutomotive": "automotive",
		"slugServices": "services",
		"slugServicesPortraiture": "portrait-photo-walks",
		"slugServicesSocialContent": "social-content-creation",
		"slugServicesAutomotive": "automotive-photography",
		"slugPhotoWalks": "photo-walks",
		"slugContact": "contact",
		"slugGear": "gear",

		"homepageTitle": "I create outdoor portraits on relaxed photowalks in and around Budapest.",
		"homepageButton": "Let's Walk",
		"homepageLink": "or check out my work",

	},
	hu: {
		"siteTitle": "Szabó Roland Fotográfia",
		"copyright": "Minden jog fenntartva.",

		"photoBy": "Fotó:",
		"photoAndEditBy": "Fotó és szerkesztés:",
		"peterLakinger": "Lakinger Péter",
		"csanadAlfoldi": "Alföldi Csanád",
		"danosNemeth": "Németh Dános",

		"headerName": "Szabó Roland",
		"headerDescription": "Budapesti Fotós",

		"navAbout": "Rólam",
		"navGalleries": "Galériák",
		"navGalleriesPortraiture": "Portré",
		"navGalleriesSocialContent": "Közösségi Tartalom",
		"navGalleriesAutomotive": "Autó",
		"navServices": "Szolgáltatások",
		"navServicesPortraiture": "Portrézós Fotós Séták",
		"navServicesSocialContent": "Közösségi Tartalomgyártás",
		"navServicesAutomotive": "Új- és Használtautó Fotózás",
		"navPhotoWalks": "Fotós Séták",
		"navContact": "Kapcsolat",
		"navGear": "Felszerelés",

		"slugAbout": "rolam",
		"slugGalleries": "galeriak",
		"slugGalleriesPortraiture": "portre",
		"slugGalleriesSocialContent": "kozossegi-tartalom",
		"slugGalleriesAutomotive": "auto",
		"slugServices": "szolgaltatasok",
		"slugServicesPortraiture": "portre-fotos-setak",
		"slugServicesSocialContent": "kozossegi-tartalomgyartas",
		"slugServicesAutomotive": "auto-fotozas",
		"slugPhotoWalks": "fotos-setak",
		"slugContact": "kapcsolat",
		"slugGear": "felszereles",

		"homepageTitle": "Portrékat készítek kültéri fotós sétákon Budapesten és környékén.",
		"homepageButton": "Sétáljunk",
		"homepageLink": "vagy nézd meg a munkáimat",

	},
};
