function createReview({ hu, en, reviewsPage, ...review }) {
	return {
		...review,
		rating: 5,
		...(reviewsPage ? { reviewsPageSection: reviewsPage[0], reviewsPageOrder: reviewsPage[1] } : {}),
		hu: { name: hu[0], excerpt: hu[1] },
		en: { name: en[0], excerpt: en[1] },
	};
}

module.exports = {
	labels: {
		hu: {
			ratingLabel: "5 csillag az 5-ből",
			sourceLabel: "Eredeti értékelés a Google-on",
			translationLabel: "Magyar fordítás",
			serviceLabels: {
				portrait: "Portréfotózás",
				female: "Női portréfotózás",
				male: "Férfi portréfotózás",
				couple: "Páros portréfotózás",
				family: "Családi portréfotózás",
				brand: "Brand portréfotózás",
				headshot: "Headshot fotózás",
				maternity: "Kismama portréfotózás",
				engagement: "Jegyesfotózás",
				creative: "Kreatív portréfotózás",
				friendship: "Barátság fotózás",
				pets: "Kisállatos fotózás",
				"car-portrait": "Autós portréfotózás",
				automotive: "Autófotózás",
				"car-photoshoot": "Autó szépségfotózás",
				"used-car": "Használtautó fotózás",
				"business-automotive": "Céges autófotózás",
				event: "Eseményfotózás",
				wedding: "Esküvőfotózás",
				"private-event": "Családi és privát eseményfotózás",
				"corporate-event": "Céges eseményfotózás",
				corporate: "Céges fotózás",
			},
		},
		en: {
			ratingLabel: "5 out of 5 stars",
			sourceLabel: "View the original review on Google",
			translationLabel: "English translation",
			serviceLabels: {
				portrait: "Portrait photography",
				female: "Women’s portrait photography",
				male: "Men’s portrait photography",
				couple: "Couples photography",
				family: "Family photography",
				brand: "Personal brand photography",
				headshot: "Headshot photography",
				maternity: "Maternity photography",
				engagement: "Engagement photography",
				creative: "Creative portrait photography",
				friendship: "Friendship photography",
				pets: "Pet photography",
				"car-portrait": "Automotive portrait photography",
				automotive: "Automotive photography",
				"car-photoshoot": "Car beauty photography",
				"used-car": "Used car photography",
				"business-automotive": "Commercial automotive photography",
				event: "Event photography",
				wedding: "Wedding photography",
				"private-event": "Family and private event photography",
				"corporate-event": "Corporate event photography",
				corporate: "Corporate photography",
			},
		},
	},
	items: [
		createReview({
			id: "nutska",
			service: "portrait",
			suitableFor: ["portrait-hub", "female-portrait"],
			sourceLocale: "en",
			topics: ["camera-anxiety", "guidance", "atmosphere", "results"],
			googleURL: "https://maps.app.goo.gl/3jiW6qmNYSVYW7X29",
			photo: "/assets/images/testimonials/nutska.webp",
			hu: ["Nutska", "Roland mellett egyszerűen nem létezik olyan, hogy „nem fotogén”, a munkái pedig magukért beszélnek."],
			en: ["Nutska", "There is no such thing as ‘non-photogenic’ when shooting with Roland, and his results truly speak for themselves."],
			reviewsPage: ["featured", 1],
		}),
		createReview({
			id: "dani-attila",
			service: "portrait",
			suitableFor: ["portrait-hub", "male-portrait"],
			sourceLocale: "hu",
			topics: ["camera-anxiety", "guidance", "atmosphere"],
			googleURL: "https://maps.app.goo.gl/swdsX2VZghCmTY1X6",
			photo: "/assets/images/testimonials/ata.webp",
			hu: ["Dani Attila", "Egyszerűen, érthetően instruált, folyamatosan segített, megmutatta, mire számíthatok, és remekül oldotta a hangulatot. A fotózás így felszabadult és meghatározó élmény lett számomra."],
			en: ["Attila Dani", "He gave simple, clear guidance, continuously helped me, explained what to expect, and created such a relaxed atmosphere that the whole experience became genuinely freeing and memorable."],
			reviewsPage: ["guidance", 1],
		}),
		createReview({
			id: "aiganysh-k",
			service: "portrait",
			suitableFor: ["portrait-hub"],
			sourceLocale: "en",
			topics: ["camera-anxiety", "confidence", "atmosphere", "results"],
			googleURL: "https://maps.app.goo.gl/8BmDo8sfAWqQErRe7",
			photo: "/assets/images/testimonials/aiganysh.webp",
			hu: ["Aiganysh K.", "Roland kisugárzása és humora nemcsak komfortossá, hanem igazán magabiztossá is tett a kamera előtt."],
			en: ["Aiganysh K.", "Roland’s warm presence and humour made me feel not only comfortable but genuinely confident in front of the camera."],
		}),
		createReview({
			id: "horvath-karina",
			service: "portrait",
			suitableFor: ["female-portrait"],
			sourceLocale: "hu",
			topics: ["camera-anxiety", "patience", "flexibility", "confidence"],
			googleURL: "https://g.co/kgs/XZoFsBW",
			photo: "/assets/images/testimonials/karina.webp",
			hu: ["Horváth Karina", "A mindennapokban ódzkodom attól, hogy kép készüljön rólam, de Roland segített felfedezni az előnyös oldalamat."],
			en: ["Karina Horváth", "I usually shy away from having my photo taken, but Roland helped me discover my best side."],
			reviewsPage: ["camera-anxiety", 1],
		}),
		createReview({
			id: "v-nori",
			service: "portrait",
			suitableFor: ["female-portrait"],
			sourceLocale: "hu",
			topics: ["camera-anxiety", "guidance", "confidence", "results"],
			photo: "/assets/images/testimonials/nori.webp",
			hu: ["V. Nóri", "Sikerült elérnie, hogy feloldódjak, folyamatosan instruált, a végeredmény pedig gyönyörű lett."],
			en: ["Nóri V.", "He helped me relax, guided me throughout the session, and the final result was beautiful."],
		}),
		createReview({
			id: "h-gyorgy",
			service: "portrait",
			suitableFor: ["male-portrait"],
			sourceLocale: "hu",
			topics: ["first-session", "camera-anxiety", "guidance", "confidence"],
			photo: "/assets/images/testimonials/gyuri.webp",
			hu: ["H. György", "Ez volt az első fotózásom. A végére a laza hangulatnak és a hasznos pózolási tippeknek köszönhetően sokkal magabiztosabbnak éreztem magam, és remek képek készültek."],
			en: ["György H.", "It was my first photoshoot. By the end, the relaxed atmosphere and useful posing guidance had made me feel far more confident, and we created some excellent photos."],
			reviewsPage: ["guidance", 2],
		}),
		createReview({
			id: "janzso-istvan",
			service: "portrait",
			suitableFor: ["male-portrait", "automotive-portrait"],
			sourceLocale: "hu",
			topics: ["camera-anxiety", "guidance", "atmosphere", "automotive"],
			googleURL: "https://maps.app.goo.gl/HKhZiv7Q2F1sYnqG8",
			photo: "/assets/images/testimonials/istvan.webp",
			hu: ["Janzsó István", "A fotózás előtt kicsit izgultam — vagy nem is kicsit —, de sokat beszélgettünk, és a folyamat meglepően természetes lett. Kaptam instrukciókat, de nem volt semmi gépies, csak jó hangulat."],
			en: ["István Janzsó", "Before the shoot I was nervous — more than a little — but we talked a lot, and the whole process became surprisingly natural. I received guidance, but nothing felt mechanical; it was simply a great atmosphere."],
			reviewsPage: ["camera-anxiety", 3],
		}),
		createReview({
			id: "parinita-roopesh",
			service: "couple",
			suitableFor: ["couple-portrait"],
			sourceLocale: "en",
			topics: ["camera-anxiety", "guidance", "authenticity", "atmosphere"],
			googleURL: "https://g.co/kgs/dQuKF6b",
			photo: "/assets/images/testimonials/parinita-roopesh.webp",
			hu: ["Parinita & Roopesh", "Mindketten feszengünk a kamera előtt, de Roland mellett teljesen önmagunk tudtunk lenni."],
			en: ["Parinita & Roopesh", "We are both very conscious of the camera, but Roland made us feel completely at ease and able to be ourselves."],
		}),
		createReview({
			id: "klar-rachel-benedek",
			service: "couple",
			suitableFor: ["couple-portrait"],
			sourceLocale: "hu",
			topics: ["camera-anxiety", "guidance", "atmosphere"],
			googleURL: "https://maps.app.goo.gl/fVgocDDkgTvxNgLp7",
			photo: "/assets/images/testimonials/rachel-benedek.webp",
			hu: ["Klar Rachel & Benedek", "Annak ellenére, hogy szerencsétlenkedtünk a kamera előtt, végig segített ellazulni és megtalálni a megfelelő pózokat. Határozottan, mégis kedvesen instruált minket."],
			en: ["Rachel Klar & Benedek", "Even though we felt awkward in front of the camera, he helped us relax and find the right poses throughout. His guidance was confident, yet always kind."],
			reviewsPage: ["guidance", 3],
		}),
		createReview({
			id: "jackie-andre",
			service: "couple",
			suitableFor: ["couple-portrait"],
			sourceLocale: "en",
			topics: ["camera-anxiety", "atmosphere", "authenticity", "results"],
			photo: "/assets/images/testimonials/jackeline-andre.webp",
			hu: ["Jackie & André", "A fotózás elején kicsit félénkek voltunk, de sokat beszélgettünk és nevettünk, így könnyen feloldódtunk, és hihetetlenül jó képek készültek rólunk."],
			en: ["Jackie & André", "We were a little shy at the beginning, but Roland was so friendly and we talked and laughed so much that we quickly relaxed and came away with incredible photos."],
		}),
		createReview({
			id: "marie-mizokami",
			service: "family",
			suitableFor: ["family-portrait", "maternity-portrait"],
			sourceLocale: "en",
			topics: ["family", "flexibility", "patience", "results"],
			googleURL: "https://maps.app.goo.gl/dUT3ar3GBsMM4Mkt8",
			photo: "/assets/images/testimonials/marie.webp",
			hu: ["Marie Mizokami", "Szülőként különösen hálás voltam azért, hogy nem szigorú időkeretben dolgozott, ami egy gyermekkel óriási segítség volt."],
			en: ["Marie Mizokami", "As a parent, I was especially grateful that he offered a session without a strict time limit, which made it so much easier with a child."],
			reviewsPage: ["featured", 3],
		}),
		createReview({
			id: "inna-efremova",
			service: "family",
			suitableFor: ["family-portrait", "maternity-portrait"],
			sourceLocale: "en",
			topics: ["family", "baby", "organisation", "results"],
			googleURL: "https://maps.app.goo.gl/LALfJ8qKP9UTdF8FA",
			photo: "/assets/images/testimonials/inna.webp",
			hu: ["Inna Efremova", "Egy kisbabával érkeztünk, ezért aggódtunk előtte, de minden gördülékenyen, gyorsan és profin zajlott."],
			en: ["Inna Efremova", "We arrived with a small baby and were worried beforehand, but everything was smooth, quick and professional."],
		}),
		createReview({
			id: "altjin-baysa",
			service: "family",
			suitableFor: ["family-portrait"],
			sourceLocale: "en",
			topics: ["family", "atmosphere", "confidence", "results"],
			photo: "/assets/images/testimonials/altjin-baysa.webp",
			hu: ["Altjin & Baysa", "A családommal együtt nyugodtnak és magabiztosnak éreztük magunkat a fotózás alatt; a szolgáltatás és maga az élmény is csúcsminőségű volt."],
			en: ["Altjin & Baysa", "My family and I felt relaxed and confident throughout the shoot; both the service and the experience itself were truly first-rate."],
		}),
		createReview({
			id: "sven-wenzel",
			service: "corporate",
			suitableFor: ["brand-portrait", "business-automotive"],
			sourceLocale: "hu",
			topics: ["branding", "planning", "versatility", "results"],
			googleURL: "https://maps.app.goo.gl/MWtg2xUQimzGayT26",
			photo: "/assets/images/testimonials/sven.webp",
			hu: ["Sven Wenzel", "A stúdiós professzionális portréktól a városi, autentikus képekig fantasztikus eredmények születtek, és a fotózás során végig teljesen otthon éreztem magam."],
			en: ["Sven Wenzel", "From professional studio portraits to authentic images around the city, the results were fantastic, and I felt completely at ease throughout the shoot."],
		}),
		createReview({
			id: "emmylou",
			service: "headshot",
			suitableFor: ["brand-portrait", "headshot"],
			sourceLocale: "en",
			topics: ["brief", "guidance", "camera-anxiety", "organisation"],
			googleURL: "https://maps.app.goo.gl/MFanSADVwY3Hwa2FA",
			photo: "/assets/images/testimonials/emmylou.webp",
			hu: ["Emmylou", "Időt szánt arra, hogy megértse az elképzeléseimet, és végig egyértelműen kommunikált, amitől sokkal felszabadultabban éreztem magam a kamera előtt."],
			en: ["Emmylou", "He took the time to understand my expectations and communicated clearly throughout, which helped me feel far more comfortable in front of the camera."],
		}),
		createReview({
			id: "g-mici",
			service: "portrait",
			suitableFor: ["brand-portrait"],
			sourceLocale: "hu",
			topics: ["brief", "atmosphere", "flexibility", "results"],
			photo: "/assets/images/testimonials/mici.webp",
			hu: ["G. Mici", "A fotózás alatt gondoskodott az oldott hangulatról, könnyen megtaláltuk a közös hangot, és tökéletesen eltalálta az elképzelésemet."],
			en: ["Mici G.", "He created a relaxed atmosphere, we quickly found common ground, and he captured my ideas perfectly."],
		}),
		createReview({
			id: "willie-alexa",
			service: "family",
			suitableFor: ["maternity-portrait"],
			sourceLocale: "en",
			topics: ["maternity", "milestone", "planning", "results"],
			googleURL: "https://g.co/kgs/VZdMhQp",
			photo: "/assets/images/testimonials/willie.webp",
			hu: ["Willie & Alexa", "Nem is választhattunk volna jobb fotóst életünk ezen kiemelkedően fontos mérföldkövéhez, az első várandósságunk megörökítéséhez."],
			en: ["Willie & Alexa", "We could not have chosen a better photographer for this important milestone in our lives: our first pregnancy."],
		}),
		createReview({
			id: "gyertyas-nora",
			service: "couple",
			suitableFor: ["engagement"],
			sourceLocale: "hu",
			topics: ["engagement", "brief", "patience", "atmosphere"],
			googleURL: "https://maps.app.goo.gl/L1TeUvN3TjMFspiT6",
			photo: "/assets/images/testimonials/nora.webp",
			hu: ["Gyertyás Nóra", "Nem siettetett minket, segített megvalósítani az elképzelt koncepciónkat, és rövid idő után tényleg feloldódtunk."],
			en: ["Nóra Gyertyás", "He never rushed us, helped bring our concept to life, and before long we genuinely relaxed in front of the camera."],
		}),
		createReview({
			id: "pahoki-timea-furkan",
			service: "couple",
			suitableFor: ["engagement"],
			sourceLocale: "hu",
			topics: ["engagement", "camera-anxiety", "atmosphere", "care"],
			googleURL: "https://maps.app.goo.gl/jLm4BaHmTWPFZESz8",
			photo: "/assets/images/testimonials/timi-furkan.webp",
			hu: ["Páhoki Tímea & Furkan", "Roland mindig segített felszabadulni a fotózások során, és valóban szívvel-lélekkel, hozzáértéssel végzi a munkáját."],
			en: ["Tímea Páhoki & Furkan", "Roland always helped us relax during our shoots, and he genuinely approaches his work with expertise, heart and soul."],
		}),
		createReview({
			id: "noszlopi-dominik",
			service: "event",
			suitableFor: ["engagement", "private-event"],
			sourceLocale: "hu",
			topics: ["engagement", "wedding", "natural-moments", "fast-delivery"],
			googleURL: "https://maps.app.goo.gl/XtyqLftvDwf8mYDc9",
			photo: "/assets/images/testimonials/dominik-eszter.webp",
			hu: ["Noszlopi Dominik", "Már az ismerkedős alkalom is nagyon jó hangulatban telt, a nagy napon pedig egész délután és este figyelmesen kereste a megörökítésre érdemes pillanatokat és életképeket."],
			en: ["Dominik Noszlopi", "Even our introductory session had a wonderful atmosphere, and on the wedding day he spent the entire afternoon and evening attentively looking for meaningful moments and natural scenes to preserve."],
		}),
		createReview({
			id: "horvath-orsolya",
			service: "portrait",
			suitableFor: ["creative-portrait"],
			sourceLocale: "hu",
			topics: ["creativity", "collaboration", "atmosphere", "results"],
			googleURL: "https://maps.app.goo.gl/Z8QqM2tMvAb8dw8Z7",
			photo: "/assets/images/testimonials/orsi.webp",
			hu: ["Horváth Orsolya", "A fotózások nemcsak szuper eredményeket hoznak, hanem mindig jó hangulatban telnek; a közös munka inspiráló és gördülékeny."],
			en: ["Orsolya Horváth", "The sessions not only produce excellent results, but are always filled with a great atmosphere; working together is inspiring and effortless."],
		}),
		createReview({
			id: "e-vivien",
			service: "portrait",
			suitableFor: ["creative-portrait"],
			sourceLocale: "hu",
			topics: ["creativity", "brief", "collaboration", "results"],
			photo: "/assets/images/testimonials/vivien.webp",
			hu: ["É. Vivien", "Roland csodásan megvalósítja azokat a képeket, amelyeket a fejemben elképzelek."],
			en: ["Vivien É.", "Roland brings the images I imagine to life beautifully."],
		}),
		createReview({
			id: "muskan-k",
			service: "portrait",
			suitableFor: ["creative-portrait"],
			sourceLocale: "en",
			topics: ["creative", "camera-anxiety", "confidence", "atmosphere"],
			photo: "/assets/images/testimonials/muskan.webp",
			hu: ["K. Muskan", "Szégyenlős vagyok a kamera előtt, de Roland a fotózás során minden félelmemet elfeledtette velem, és végig magabiztosnak éreztem magam."],
			en: ["Muskan K.", "I am camera-shy, but Roland made me forget all my fears during the shoot and helped me feel confident throughout."],
		}),
		createReview({
			id: "vorosilov-veronika",
			service: "portrait",
			suitableFor: ["friendship"],
			sourceLocale: "hu",
			topics: ["friendship", "spontaneity", "atmosphere", "results"],
			googleURL: "https://maps.app.goo.gl/xtwbxAtdjctgahnD7",
			photo: "/assets/images/testimonials/veronika-2.webp",
			hu: ["Vorosilov Veronika", "Az eredetileg csajos programnak induló délután rendkívül jó hangulatú profi fotózássá alakult, és elképesztően csodás képek születtek."],
			en: ["Veronika Vorosilov", "What began as a girls’ day out turned into a wonderfully relaxed professional photoshoot, producing absolutely beautiful images."],
		}),
		createReview({
			id: "eperjesi-julia",
			service: "portrait",
			suitableFor: ["friendship"],
			sourceLocale: "hu",
			topics: ["friendship", "communication", "fast-delivery", "results"],
			googleURL: "https://maps.app.goo.gl/1UtYMiykdfV9921g8",
			photo: "/assets/images/testimonials/sky.webp",
			hu: ["Eperjesi Júlia", "Nagyon profin és kedvesen kommunikált, és 48 órán belül megkaptuk a kész, szerkesztett képeket."],
			en: ["Júlia Eperjesi", "He communicated in such a kind and professional way, and we received the finished, edited images within 48 hours."],
		}),
		createReview({
			id: "szeker-dalma",
			service: "portrait",
			suitableFor: ["friendship", "pet-portrait"],
			sourceLocale: "hu",
			topics: ["friendship", "attention", "atmosphere"],
			googleURL: "https://maps.app.goo.gl/ZP4SjhQ7dtp7hMEf6",
			photo: "/assets/images/testimonials/dalma.webp",
			hu: ["Szekér Dalma", "Többször dolgoztunk már együtt Rolanddal; minden könnyedén ment vele, figyelmes és nagyon ügyes fotós."],
			en: ["Dalma Szekér", "We have worked with Roland several times; everything has always felt easy, and he is an attentive, highly skilled photographer."],
		}),
		createReview({
			id: "leane-stewart",
			service: "portrait",
			suitableFor: ["pet-portrait"],
			sourceLocale: "en",
			topics: ["patience", "attention", "selection", "results"],
			googleURL: "https://maps.app.goo.gl/bpyqd84Z23e2hxf8A",
			photo: "/assets/images/testimonials/leane.webp",
			hu: ["Leané Stewart", "Türelmes volt, időt szánt arra, hogy minden részlet tökéletes legyen, és hogy teljesen elégedett legyek a kiválasztott képekkel."],
			en: ["Leané Stewart", "He was patient, took the time to ensure every detail was right, and made sure I was completely happy with the selected images."],
		}),
		createReview({
			id: "sheila",
			service: "portrait",
			suitableFor: ["pet-portrait"],
			sourceLocale: "en",
			topics: ["camera-anxiety", "authenticity", "attention", "results"],
			googleURL: "https://maps.app.goo.gl/wKJQz4xfkrR8bstX6",
			photo: "/assets/images/testimonials/sheila.webp",
			hu: ["Sheila", "Az igazi erőssége abban rejlik, hogy olyan komfortosan érzed magad mellette, hogy a legtermészetesebb önmagad tud megjelenni a kamera előtt."],
			en: ["Sheila", "His true gift is making you feel comfortable enough to bring out your most natural self in front of the camera."],
		}),
		createReview({
			id: "banhegyi-norbert",
			service: "automotive",
			suitableFor: ["automotive-portrait", "car-photoshoot"],
			sourceLocale: "hu",
			topics: ["automotive", "atmosphere", "results"],
			googleURL: "https://maps.app.goo.gl/61BK1HHCmQdpP2W49",
			photo: "/assets/images/testimonials/cars_e92.webp",
			hu: ["Bánhegyi Norbert", "Nagyon jó hangulatú fotózás volt az első perctől kezdve. A végeredmény pedig profi munka."],
			en: ["Norbert Bánhegyi", "The photoshoot had a great atmosphere from the very first minute, and the final result was truly professional."],
		}),
		createReview({
			id: "botlik-tamas",
			service: "automotive",
			suitableFor: ["automotive-portrait", "used-car"],
			sourceLocale: "hu",
			topics: ["automotive", "organisation", "efficiency", "results"],
			googleURL: "https://maps.app.goo.gl/Ub345tTkCSm9rNFY8",
			photo: "/assets/images/testimonials/cars_bmw-1.webp",
			hu: ["Botlik Tamás", "A helyszín, az időpont és az autó beállításának egyeztetése gyors és hatékony volt, a képek pedig nagyon jók lettek."],
			en: ["Tamás Botlik", "Arranging the location, timing and positioning of the car was quick and efficient, and the photos turned out excellent."],
		}),
		createReview({
			id: "claire-jakeman",
			service: "headshot",
			suitableFor: ["headshot"],
			sourceLocale: "en",
			topics: ["headshot", "camera-anxiety", "guidance", "atmosphere"],
			googleURL: "https://maps.app.goo.gl/ZsRPs7YtAD1brRiz6",
			photo: "/assets/images/testimonials/claire.webp",
			hu: ["Claire Jakeman", "Olyan emberként, aki nem igazán szeret kamera elé állni, különösen értékeltem, mennyire könnyedén oldotta a feszültséget és segített komfortosan érezni magam a fotózás alatt."],
			en: ["Claire Jakeman", "As someone who does not enjoy having their photograph taken, I particularly appreciated how easily Roland put me at ease in front of the camera."],
			reviewsPage: ["camera-anxiety", 2],
		}),
		createReview({
			id: "ryan-henderson",
			service: "headshot",
			suitableFor: ["headshot"],
			sourceLocale: "en",
			topics: ["headshot", "team", "organisation", "camera-anxiety"],
			googleURL: "https://maps.app.goo.gl/cSUrnjAfwmvgwakBA",
			photo: "/assets/images/testimonials/ryan.webp",
			hu: ["Ryan Henderson", "A fotózás alatt mindenkit megnyugtatott és oldott hangulatot teremtett, ami hatalmas különbséget jelentett, és a végeredményen is látszik."],
			en: ["Ryan Henderson", "He put everyone at ease throughout the shoot, which made a huge difference and clearly shows in the final images."],
		}),
		createReview({
			id: "gombos-barnabas",
			service: "automotive",
			suitableFor: ["automotive-hub", "used-car"],
			sourceLocale: "hu",
			topics: ["used-car", "business-result", "organisation", "results"],
			googleURL: "https://g.co/kgs/iHjEqtt",
			photo: "/assets/images/testimonials/cars_ceed-sw.webp",
			hu: ["Gombos Barnabás", "Az új fotók feltöltése után napokon belül elvitték az autót. Úgy gondolom, Roland segítsége nélkül még most is árulnám."],
			en: ["Barnabás Gombos", "Within days of uploading the new photos, the car was sold. I think I would still be trying to sell it without Roland’s help."],
			reviewsPage: ["complex-work", 3],
		}),
		createReview({
			id: "gergo-nadine-bus",
			service: "automotive",
			suitableFor: ["automotive-hub", "business-automotive"],
			sourceLocale: "hu",
			topics: ["automotive", "collaboration", "results"],
			googleURL: "https://maps.app.goo.gl/BrfWFg8YswLxYiNE8",
			photo: "/assets/images/testimonials/cars_nadine-bus.webp",
			hu: ["Gergő, Nadine Bus", "Nagyon jó volt Rolanddal dolgozni, a végeredmény pedig magáért beszél."],
			en: ["Gergő, Nadine Bus", "It was a pleasure working with Roland, and the final result speaks for itself."],
		}),
		createReview({
			id: "bacsek-richard",
			service: "automotive",
			suitableFor: ["automotive-hub", "car-photoshoot"],
			sourceLocale: "hu",
			topics: ["automotive", "atmosphere", "fast-delivery", "results"],
			googleURL: "https://maps.app.goo.gl/2x345YFXpSaHMNsZ8",
			photo: "/assets/images/testimonials/cars_mondeo.webp",
			hu: ["Bacsek Richárd", "Jó hangulatú fotózás, gyors utómunka és tökéletes fotók."],
			en: ["Richárd Bacsek", "A great atmosphere during the shoot, fast editing and excellent photos."],
		}),
		createReview({
			id: "emmert-armin",
			service: "automotive",
			suitableFor: ["car-photoshoot", "used-car"],
			sourceLocale: "hu",
			topics: ["automotive", "planning", "brief", "guidance", "fast-delivery"],
			googleURL: "https://maps.app.goo.gl/gM39RUXmVzxxQJUt6",
			photo: "/assets/images/testimonials/cars_corsa-e.webp",
			hu: ["Emmert Ármin", "Azonnal megértette és figyelembe vette a különleges kéréseimet. Pontosan tudta, mit csinál, és a fotózás közben is határozottan instruált."],
			en: ["Ármin Emmert", "He immediately understood and respected my specific requests. He clearly knew what he was doing and gave confident guidance throughout the car shoot."],
		}),
		createReview({
			id: "corina-haro",
			service: "corporate",
			suitableFor: ["business-automotive"],
			sourceLocale: "en",
			topics: ["commercial", "professionalism", "brief", "results"],
			googleURL: "https://maps.app.goo.gl/tkBCrcYgoqdPRUCj9",
			photo: "/assets/images/testimonials/corina.webp",
			hu: ["Corina Haro", "Roland nagyszerű fotós, barátságos és rendkívül profi. A professzionális képanyagunk frissítésére készült stúdiós fotózás végeredményével maximálisan elégedettek voltunk."],
			en: ["Corina Haro", "Roland is a great photographer: friendly and highly professional. We were delighted with the results of the studio shoot created to update our professional imagery."],
		}),
		createReview({
			id: "becseri-vivien",
			service: "event",
			suitableFor: ["event-hub", "wedding"],
			sourceLocale: "hu",
			topics: ["wedding", "full-day", "atmosphere", "fast-delivery"],
			googleURL: "https://maps.app.goo.gl/jGmGMDAUwRy6U9ur7",
			photo: "/assets/images/testimonials/vivien-4.webp",
			hu: ["Becséri Vivien", "A készülődéstől a buli végéig velünk volt; a profizmus mellett a humor és a jókedv is végig határtalan volt, az utómunka pedig elképesztően gyors."],
			en: ["Vivien Becséri", "He was with us from the preparations until the end of the party; alongside his professionalism, the humour and joy were boundless, and the editing was incredibly fast."],
		}),
		createReview({
			id: "charlie-wells",
			service: "event",
			suitableFor: ["event-hub"],
			sourceLocale: "en",
			topics: ["event", "planning", "reliability", "difficult-lighting"],
			googleURL: "https://maps.app.goo.gl/RhApN65rKhXn2fHSA",
			photo: "/assets/images/testimonials/charlie.webp",
			hu: ["Charlie Wells", "Minden részletre gondolt, mindenre gyorsan reagált, és teljesen felkészülten érkezett. A képek a nehéz fényviszonyok ellenére is tökéletesek lettek."],
			en: ["Charlie Wells", "He thought of every detail, was highly responsive, and arrived completely prepared. The photos came out perfectly despite the difficult lighting."],
			reviewsPage: ["complex-work", 2],
		}),
		createReview({
			id: "lynne-fisher",
			service: "corporate",
			suitableFor: ["event-hub", "corporate-event"],
			sourceLocale: "en",
			topics: ["corporate-event", "camera-anxiety", "flexibility", "organisation", "results"],
			googleURL: "https://maps.app.goo.gl/Bh3CdfsPH77sCyeJA",
			photo: "/assets/images/testimonials/lynne.webp",
			hu: ["Lynne Fisher", "A csapatunkból sokan egyáltalán nem érzik magukat természetesen fotózás közben, de Roland nyugodt, barátságos hozzáállása segített mindenkinek ellazulni és élvezni a pillanatot."],
			en: ["Lynne Fisher", "Many of our team are not naturally comfortable in front of a camera, yet Roland’s calm, friendly manner helped everyone relax and enjoy the moment."],
			reviewsPage: ["featured", 2],
		}),
		createReview({
			id: "nijat-polina",
			service: "event",
			suitableFor: ["wedding"],
			sourceLocale: "en",
			topics: ["wedding", "full-day", "guidance", "care"],
			googleURL: "https://g.co/kgs/pdkE31B",
			photo: "/assets/images/testimonials/polina-nijat.webp",
			hu: ["Nijat & Polina", "Közel kilenc órán át fáradhatatlanul örökítette meg az esküvőnket, és minden fontos pillanatról kaptunk képet."],
			en: ["Nijat & Polina", "He worked tirelessly for nearly nine hours to capture our wedding, and we received photographs of every important moment."],
		}),
		createReview({
			id: "burcu-sebastian",
			service: "event",
			suitableFor: ["wedding"],
			sourceLocale: "en",
			topics: ["wedding", "natural-moments", "authenticity", "results"],
			photo: "/assets/images/testimonials/burcu-sebastian.webp",
			hu: ["Burcu & Sebastian", "Gyönyörűen örökítette meg a spontán és valódi pillanatokat is, maradandó emlékeket teremtve nekünk."],
			en: ["Burcu & Sebastian", "He captured the spontaneous and genuine moments beautifully, creating lasting memories for us."],
		}),
		createReview({
			id: "mate-barbara",
			service: "event",
			suitableFor: ["private-event"],
			sourceLocale: "hu",
			topics: ["event", "guidance", "flexibility", "organisation", "natural-moments"],
			googleURL: "https://maps.app.goo.gl/v3AKq7CEbRjvP6ZJ6",
			photo: "/assets/images/testimonials/mate-barbara.webp",
			hu: ["Máté Barbara", "Gyorsan, jó instrukciókkal készítette el a közös képeket, közben pedig mindenütt ott volt, és elcsípte a fontos pillanatokat."],
			en: ["Barbara Máté", "He took the group photos quickly and with clear guidance, while also being everywhere at once to catch the important moments."],
			reviewsPage: ["complex-work", 1],
		}),
		createReview({
			id: "ofir-shalit",
			service: "event",
			suitableFor: ["private-event"],
			sourceLocale: "en",
			topics: ["event", "guidance", "natural-moments", "storytelling"],
			googleURL: "https://maps.app.goo.gl/b8C9WqrTzg6iyoJV7",
			photo: "/assets/images/testimonials/ofir.webp",
			hu: ["Ofir Shalit", "Pontosan tudja, hogyan vezessen végig egy fotózást, és olyan természetes helyzeteket teremtsen, amelyekből valódi érzelmekkel teli, történetet mesélő képek születnek."],
			en: ["Ofir Shalit", "He knows exactly how to guide a photoshoot and create natural situations that bring out genuine emotion, making every photograph feel alive and meaningful."],
		}),
		createReview({
			id: "anca-radu",
			service: "corporate",
			suitableFor: ["corporate-event"],
			sourceLocale: "en",
			topics: ["corporate-event", "guidance", "organisation", "attention"],
			googleURL: "https://maps.app.goo.gl/D6q73MbDqu5du3DK9",
			photo: "/assets/images/testimonials/anca.webp",
			hu: ["Anca Radu", "Időt szánt arra, hogy végigvezessen a folyamaton, és segítsen abban, hogyan készülhetnek a lehető legjobb képek. Lenyűgöző volt, mennyi figyelmet fordított mindenkire a kétnapos céges esemény alatt."],
			en: ["Anca Radu", "He took the time to talk me through the process and guide me towards the best possible photos. His involvement and attention throughout the two-day company event were incredibly impressive."],
		}),
		createReview({
			id: "lisa-walker",
			service: "corporate",
			suitableFor: ["corporate-event"],
			sourceLocale: "en",
			topics: ["corporate-event", "professionalism", "insight", "approachability"],
			googleURL: "https://maps.app.goo.gl/EPSrYdY9USKe6ecE7",
			photo: "/assets/images/testimonials/lisa.webp",
			hu: ["Lisa Walker", "A profizmusa, a meglátásai és a közvetlen hozzáállása messze felülmúlta az elvárásainkat."],
			en: ["Lisa Walker", "His professionalism, insight and approachability went far beyond what we expected."],
		}),
	],
};
