module.exports = {
	items: [
		{
			type: "couple",
			score: "5.0",
			photo: "/assets/images/testimonials/szilvi-laci.webp",
			hu: {
				name: "M. Szilvi",
				excerpt: "Roland gyorsan elérte, hogy ellazuljunk a kamera előtt, mivel nem vagyunk rutinosak",
				text: "Rolival nagyon kellemes volt a fotózás. Jó hangulatban telt, elkapta a legjobb pillanatokat. Gyorsan elérte, hogy ellazuljunk a kamera előtt, mivel nem vagyunk rutinosak. Profi az egész, amit csinál, a végeredmény pedig magáért beszél; gyönyörűek a képek. Szívből ajánljuk őt!",
				link: "/hu/portre/szilvi-laci/",
			},
			en: {
				name: "Szilvi M.",
				excerpt: "He quickly made us relax in front of the camera, as we are not experienced",
				text: "It was a very pleasant photo session with Roli. We had a good atmosphere, and he managed to catch the best moments. He quickly made us relax in front of the camera, as we are not experienced. What he does is professional and the end result speaks for itself, the pictures are beautiful. We heartily recommend him!",
				link: "/en/portraiture/szilvi-laci/",
			},
		},
		// {
		// 	type: "male",
		// 	score: "",
		// 	photo: "/assets/images/testimonials/.webp",
		// 	hu: {
		// 		name: "",
		// 		excerpt: "",
		// 		text: "",
		// 		link: "/hu/portre//",
		// 	},
		// 	en: {
		// 		name: "",
		// 		excerpt: "",
		// 		text: "",
		// 		link: "/en/portraiture//",
		// 	},
		// },
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/blanka.webp",
			hu: {
				name: "M. Blanka",
				excerpt: "Igazán különlegesnek érezhettem magam a fotózásunk alatt",
				text: "Egy csodálatos fotózást kaptam Rolandtól. Nagyon hidegben került sor a szabadtéri fotózásunkra, ami igencsak komoly kihívást jelentett, azonban ezen körülmények között is minden percét élveztem. Roland gyorsasága, precízsége és felkészültsége páratlan volt. Mindent megtett annak érdekében, hogy jól érezzem magam. Rengeteg segítséget nyújtott a legelőnyösebb pózok megtalálásában is, aminek szintén nagyon örültem. Nem “csak” fotókkal, hanem egy óriási élménnyel lehetsz gazdagabb, ha Rolandot választod! Én mindent megkaptam tőle, amit csak lehetett és igazán különlegesnek érezhettem magam a fotózásunk alatt. Csakis ajánlani tudom őt. Az biztos, hogy én még a jövőben is szeretnék dolgozni vele!",
				link: "/hu/portre/blanka-3/",
			},
			en: {
				name: "Blanka M.",
				excerpt: "Roland made me feel truly special during our photo session",
				text: "I had a wonderful photo session with Roland. Our outdoor shoot took place in very cold conditions, which was quite challenging, but I still enjoyed every minute of it. Roland's speed, precision and preparation were second to none. He did everything he could to make me feel comfortable. He also gave me a lot of help in finding the most advantageous poses, which I was very happy about. You will not only get photos, but a great experience as well if you choose Roland! He delivered everything he possibly could and made me feel truly special during our photo session. I can only recommend him. I would definitely like to work with him in the future!",
				link: "/en/portraiture/blanka-3/",
			},
		},
		{
			type: "couple",
			score: "5.0",
			photo: "/assets/images/testimonials/betti-laci.webp",
			hu: {
				name: "M. Betti & P. Laci",
				excerpt: "Roland igyekezte elkapni a kedves pillanatokat, amikből csodálatos képek születtek.",
				text: "Párommal jegyes fotózáson vettünk részt, mindkettőnk számára új élmény volt maga a fotózás is. Tartottunk is tőle, de mindkettőnk számára pozitív csalódás volt, és csupa szuper élménnyel gazdagodtunk. Roland igyekezte elkapni a kedves pillanatokat, amikből csodálatos képek születtek.",
				link: "/hu/portre/betti-laci/",
			},
			en: {
				name: "Betti M. & Laci P.",
				excerpt: "Roland made sure to capture the lovely moments that resulted in wonderful pictures.",
				text: "My partner and I attended an engagement shoot, and for both of us it was a new experience. We were a bit apprehensive, but it was a positive disappointment for both of us and we had a great experience. Roland made sure to capture the lovely moments that resulted in wonderful pictures.",
				link: "/en/portraiture/betti-laci/",
			},
		},
		{
			type: "couple",
			score: "5.0",
			photo: "/assets/images/testimonials/zsuzsika-gyuri.webp",
			hu: {
				name: "P. Zsuzsika & B. Gyuri",
				excerpt: "Meglepően természetes módon viselkedtünk Roland kamerája előtt",
				text: "Nagyon kellemes hangulatú fotózás volt, meglepően természetes módon viselkedtünk Roland kamerája előtt, ami a képeken is visszatükröződött. Bátran és szívből ajánljuk!",
				link: "/hu/portre/zsuzsika-gyuri/",
			},
			en: {
				name: "Zsuzsika P. & Gyuri B.",
				excerpt: "We behaved in a surprisingly natural way in front of Roland's camera",
				text: "It was a very pleasant photo session, we behaved in a surprisingly natural way in front of Roland's camera, which was reflected in the pictures. We highly recommend him!",
				link: "/en/portraiture/zsuzsika-gyuri/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/laura-2.webp",
			hu: {
				name: "Laura Sz.",
				excerpt: "Roland mindig mondott valamit, amitől őszintén mosolyogni tudtam, és ezt kiadják a képek is",
				text: "Szerintem nagyon ritka, amikor valakivel ennyire jól együtt lehet dolgozni, mint Rolanddal. Nagyon sok mindent tudtam meg a pózolásról és személyre szabottan is adott tippeket. Az egész fotózás nagyon könnyed hangulatban telt, nagyon könnyű vele beszélgetni. Én sosem szerettem azokat a képeimet, amiken teljesen mosolygok, mindig nagyon erőltetettnek tűntek; viszont most volt először olyan, hogy tetszettek ilyen képek magamról. Roland mindig mondott valamit, amitől őszintén mosolyogni tudtam, és ezt kiadják a képek is. Profi munkát végez, a kattintástól az utómunkáig; nagyon tetszett a szerkesztés is, pont olyanra képzeltem a képeket, amilyenekre megcsinálta. Nagyon türelmes volt végig és megbízható is. Nagyon jó a kommunikációja, egyenes instrukciókat ad; látszik, hogy szereti amit csinál és lelkes is.",
				link: "/hu/portre/laura-2/",
			},
			en: {
				name: "Sz. Laura",
				excerpt: "Roland always said something that made me genuinely smile, and the pictures show that",
				text: "I think it's very rare to work with someone as well as Roland. I've learned a lot about posing and he gave personalized tips during our shoot. The entire photo shoot was filled with a very light atmosphere, it was very easy to talk to him. I never liked those pictures of myself in which I am fully smiling, they always looked very forced; however, this was the first time that I liked such pictures of myself. Roland always said something that made me genuinely smile, and the pictures show that. He does a professional job, from the clicks to the post-production. I also really liked the editing, I imagined the pictures to be exactly the way he'd made them. He was very patient throughout the shoot and very reliable. His communication is very good, he gives straightforward instructions; it seems that he loves what he does and is very enthusiastic.",
				link: "/en/portraiture/laura-2/",
			},
		},
		{
			type: "couple",
			score: "5.0",
			photo: "/assets/images/testimonials/klemi-adam.webp",
			hu: {
				name: "S. Klementina & L. Ádám",
				excerpt: "A kezdeti bátortalanságot gyorsan feloldották Roland poénos és segítő “utasításai”",
				text: "Amilyen spontán ötlet volt a fotózás, pontosan olyan könnyedén megkaptuk a közös hangot Rolanddal. Volt egy kis izgalom bennünk, mivel nem mozgunk rutinosan a fényképezőgép előtt, de a kezdeti bátortalanságot gyorsan feloldották Roland poénos és segítő “utasításai”. A szuper hangulat és csodás fotók garantáltak!",
				link: "/hu/portre/klemi-adam/",
			},
			en: {
				name: "Klementina S. & Ádám L.",
				excerpt: "Our initial timidity was quickly overcome by Roland's funny and helpful “instructions”",
				text: "As spontaneous as the idea of photography was, we found common ground with Roland just as easily. We were a bit nervous as we don't routinely move in front of the camera, but our initial timidity was quickly overcome by Roland's funny and helpful “instructions”. Great atmosphere and wonderful photos are guaranteed!",
				link: "/en/portraiture/klemi-adam/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/sara.webp",
			hu: {
				name: "Sara T.",
				excerpt: "A fotózásunk első pillanattól kezdve kényelmesen és magabiztosnak éreztem magam a kamera előtt",
				text: "Nagyon szerettem Rolanddal dolgozni! A fotózásunk első pillanattól kezdve kényelmesen és magabiztosnak éreztem magam a kamera előtt. Nemcsak oldott légkört teremtett, de az élményt is hihetetlenül élvezetessé és szórakoztatóvá tette. A modellezési technikákkal kapcsolatos útmutatásai kivételesek voltak, emiatt imádtam a fotózás minden pillanatát. Összességében egy fantasztikus együttműködés volt, amitől magabiztosnak éreztem magam.",
				link: "/hu/portre/sara/",
			},
			en: {
				name: "Sara T.",
				excerpt: "His guidance on modeling techniques was exceptional, and I found myself loving every moment of it",
				text: "I absolutely adored working with Roland! From the moment we started shooting, I felt comfortable in front of the camera. Not only did he create a relaxed atmosphere, but he also made the experience incredibly enjoyable and fun. His guidance on modeling techniques was exceptional, and I found myself loving every moment of it. Overall, it was a fantastic collaboration that left me feeling confident.",
				link: "/en/portraiture/sara/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/anna-2.webp",
			hu: {
				name: "M. Anna",
				excerpt: "Roland humorával, odaadásával és a fotózás iránti szenvedélyével mindenki biztonságban, megbecsülve érezheti magát",
				text: "Aki régóta kacérkodik a gondolattal, hogy kamera elé álljon, de gátlásai vannak és nem mer lépni, jó helyen jár. Roland humorával, odaadásával és a fotózás iránti szenvedélyével mindenki biztonságban, megbecsülve érezheti magát. Aki pedig bátrabb és extra élményre vágyik, nagyon tudom ajánlani az analóg fotózást. Izgalmas, hogy a képet nem tudjuk azonnal megnézni a kijelzőn, és várnunk kell a végeredményre, amíg elő nincsenek hivatva. Eszméletlen különleges és hangulatos képek tudnak így születni!",
				link: "/hu/portre/anna-9/",
			},
			en: {
				name: "Anna M.",
				excerpt: "With Roland's humor, dedication and passion for photography, everyone can feel safe and valued",
				text: "Anyone who has been flirting with the idea of appearing in front of a camera for a long time, but has inhibitions and does not dare to act, is in the right place with Roland. With his humor, dedication and passion for photography, everyone can feel safe and valued. And for those who are braver and want an extra experience, I can highly recommend analog photography. It's exciting that we can't see the image on the screen right away, and we have to wait for the final result until they are developed. Unbelievably special and atmospheric pictures can be created this way!",
				link: "/en/portraiture/anna-9/",
			},
		},
		{
			type: "couple",
			score: "",
			photo: "/assets/images/testimonials/burcu-sebastian.webp",
			hu: {
				name: "Burcu Z. & Sebastian C.",
				excerpt: "Gyönyörűen örökítette meg a spontán és valódi pillanatokat is, maradandó emlékeket teremtve nekünk",
				text: "Roland hihetetlen volt! Professzionalizmusa, kivételes kiszolgálása és az általa készített esküvői fotóink lenyűgöző minősége felülmúlta minden várakozásunkat. Gyönyörűen örökítette meg a spontán és valódi pillanatokat is, maradandó emlékeket teremtve nekünk. Szívből ajánljuk őt a különleges napotokra!",
				link: "/hu/portre/burcu-sebastian/",
			},
			en: {
				name: "Burcu Z. & Sebastian C.",
				excerpt: "He captured both spontaneous and genuine moments beautifully, creating lasting memories",
				text: "Roland was incredible! His professionalism, exceptional service, and the stunning quality of our wedding photos exceeded our expectations. He captured both spontaneous and genuine moments beautifully, creating lasting memories. We highly recommend him for your special day!",
				link: "/en/portraiture/burcu-sebastian/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/larae.webp",
			hu: {
				name: "LaRae Day",
				excerpt: "Lehetetlen nem szupermodellnek érezni magad a Rolanddal való fotózás közben",
				text: "Rolanddal kapcsolatos tapasztalataim egy szóban összefoglalva - KIVÉTELES. Kiváló szervezőkészséggel gondoskodott arról, hogy megfelelően felkészüljünk a fotózásunk napjára; a fotózás előtti kora reggelen felderítette a helyszínt! (Ez elég komoly elkötelezettség!) A fotózás során nagyon türelmes és alapos volt, hogy minden szögből, pózból és helyszínről a lehető legjobb képeket készítsük. A forgatás után számtalan órát töltött a fotóim művészi szerkesztésével, még a személyes preferenciáimat és az üzleti igényeinket is előtérbe helyezte. Emellett őszintén hiszem, hogy lehetetlen nem szupermodellnek érezni magad a Rolanddal való fotózás közben, ugyanis végig veled van és segít neked a fotózás elejétől a végéig! Annak ellenére, hogy a fotózásunk órákon át tartozz, a túláradó pozitív energiakészlete soha nem szűnt meg, és azt is meg kell említenem, hogy ez egy kora reggeli napkeltés fotózás volt, az első napsugaraktól kezdve ott voltunk. Foglalj időpontot Rolanddal MÉG MA. Bátran támogathatom Rolandot ezzel az ígérettel – nekem elhiheted, nem fogsz csalódni!",
				link: "/hu/portre/larae/",
			},
			en: {
				name: "LaRae Day",
				excerpt: "It's impossible not to feel like a supermodel while shooting with Roland",
				text: "To summarize my experience working with Roland in one word - EXCEPTIONAL. With prime organizational skills, he ensured we were properly prepared for our photoshoot day; he even scouted our location at sunrise, prior to our photoshoot day! (Now that's some serious commitment!) During the photoshoot, he was very patient and thorough in ensuring we had gotten the very best possible photos out of every angle, pose, and location. After the shoot, he spent countless hours editing our gallery to utter perfection, even taking into consideration my personal preferences and business needs for our photos. I also sincerely believe it's impossible not to feel like a supermodel while shooting with Roland because he will be verbally cheering you on from start to finish! Even though our shoot spanned hours, his contagious positive energy supply never gave out, and I should also mention this was an early morning sunrise shoot, literally taking place at the crack of dawn. Book your own photoshoot with Roland TODAY. I can confidently endorse Roland with this promise - you will not be disappointed!",
				link: "/en/portraiture/larae/",
			},
		},
		{
			type: "couple",
			score: "5.0",
			photo: "/assets/images/testimonials/rikarda-krisztian.webp",
			hu: {
				name: "N. Rikarda & Sz. Krisztián",
				excerpt: "Szívből ajánljuk Rolandot mindazoknak, akik minőségi képekben szeretnék megörökíteni a számukra különleges eseményeket, pillanatokat, egy jó hangulatú fotózás során",
				text: "Abban már a legelején biztosak voltunk, hogy a fotózás Rolanddal nagyon jó hangulatban fog telni, de arra, hogy ilyen hamar egy hullámhosszra kerülünk, és ilyen jól érezzük magunkat, nem számítottunk. A fotózás időpontja előtt alaposan átbeszéltük, milyen képeket szeretnénk, és hol, amiben Roland abszolút együttműködő volt. Teljes mértékben arra törekedett, hogy a számunkra legmegfelelőbb képeket készítse el. Rugalmassága és precízsége a profizmusának volt köszönhető, az időközben felmerülő esetleges változtatásokhoz is nyitottan állt és minden kívánságunkat meghallgatta. Maga a fotózás egy rendkívül laza, mégis dinamikus hangulatban telt. Rengeteg instrukciót kaptunk Rolandtól a fotózás ideje alatt, ami még inkább hozzájárult a fotók végeredményéhez, amik egytől-egyig magukért beszélnek. A fotózás végeztével már aznap kaptunk tőle ajándékba egyet az elkészült képek közül, és az általunk kiválasztott képeket alig pár nap alatt elkészítette. Szívből ajánljuk Rolandot mindazoknak, akik minőségi képekben szeretnék megörökíteni a számukra különleges eseményeket, pillanatokat, egy jó hangulatú fotózás során, egy profi szakemberrel.",
				link: "/hu/portre/rikarda-krisztian/",
			},
			en: {
				name: "Rikarda N. & Krisztián Sz.",
				excerpt: "We wholeheartedly recommend Roland to all those who want to capture their special events during a photo shoot with a good atmosphere",
				text: "We were sure from the very beginning that the photo shoot with Roland would be in a very good mood, but we did not expect that we would come on the same wavelength so soon and have such a good time. Before the photoshoot, we thoroughly discussed what kind of pictures we wanted and where, in which Roland was absolutely cooperative. He went out of his way to get the best pictures for us. His flexibility and precision were due to his professionalism, he was open to any changes that might arise in the meantime and he listened to all our special requests. The photo shoot itself took place in an extremely relaxed, yet dynamic atmosphere. We received a lot of instructions from Roland during the photo shoot, which contributed even more to the end result of the photos, which really speak for themselves. At the end of the photo shoot, we received one of the finalized photos as a gift on the very day of the photoshoot, and he had finalized the pictures we selected in just a few days. We wholeheartedly recommend Roland to all those who want to capture their special events and moments in high-quality pictures, during a photo shoot with a good atmosphere, with a professional photographer.",
				link: "/en/portraiture/rikarda-krisztian/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/melanie.webp",
			hu: {
				name: "Melanie B.",
				excerpt: "Öröm volt vele dolgozni, az eredmények pedig egyszerűen lenyűgözőek",
				text: "Rolanddal az év elején találkoztam először, amikor odajött hozzám az utcán, és csináltunk néhány random képet, amik csodálatosan sikerültek. Néhány hónappal ezután, a művészi pályafutásom egy nagyon fontos mérföldkőhöz érkezett, amikor is Roland a kiállításom előtt az egész délelőttöt velem töltötte, és türelmesen lefotózott az összes festményemmel. A környezet nem volt túl segítőkész, csak egy egyszerű budapesti utca, de valahogy mégis sikerült megtalálnia a tökéletes háttereket, és az alkotásaimhoz és az aznapi öltözékemhez illő színeket. Öröm volt vele dolgozni, az eredmények pedig egyszerűen lenyűgözőek.",
				link: "/hu/portre/mel/",
			},
			en: {
				name: "Melanie B.",
				excerpt: "It was a pleasure to work with him, and the results are simply amazing",
				text: "I met Roland at the beginning of the year when he approached me at the street, and we casually took some pictures, which turned out amazing. A few months after that I had a very big day in my art career, where just before the exhibition, he spent the whole morning with me, patiently taking pictures of me with all my paintings. The surroundings weren't very helpful, just a regular street in Budapest, but he managed to find the perfect backgrounds, and matching colours with my artworks, and the outfit I put on that day. It was a pleasure to work with him, and the results are simply amazing.",
				link: "/en/portraiture/mel",
			},
		},
		{
			type: "female",
			score: "4.9",
			photo: "/assets/images/testimonials/laura.webp",
			hu: {
				name: "F. Laura Hanna",
				excerpt: "Ez volt messze a legjobb fotós élményem eddig",
				text: "Bár nem ez volt az első élményem Roli fényképezőgépének a túloldalán, én hajlamos vagyok rástresszelni az ilyen alkalmakra. Nagyjából 5 perc után viszont, mintha kicseréltek volna. A szokásos viccei és poénkodása mindig feldob egy ilyen fotózást. Mivel most különösen izgatott voltam a reptéri téma miatt, nekem hatalmas élmény volt, hogy mennyi gépet láthattam elszállni felettünk. Sokat nevettünk, sokat gyönyörködtünk. De a kedvencem, hogy annak ellenére, hogy nincsenek konkrét elképzeléseim képeket illetően, valahogy mindig olyanok születnek a végén, amik maximálisan tetszenek. Ez volt messze a legjobb fotós élményem eddig.",
				link: "/hu/portre/laura/",
			},
			en: {
				name: "Laura Hanna F.",
				excerpt: "It was by far the best photography experience I've ever had",
				text: "Although this was not my first experience on the other side of Roli's camera, I tend to stress on such occasions. However, after about 5 minutes, it was as if I had been replaced. His usual jokes and banter always liven up a photoshoot like this. Since I was particularly excited about the airport theme, it was a great experience for me to see how many planes landed right above us. We laughed a lot, and enjoyed the process a lot. But my favorite thing is that, despite the fact that I don't have specific ideas about photos, I always end up with beautiful pictures that I really like. It was by far the best photography experience I've ever had.",
				link: "/en/portraiture/laura/",
			},
		},
		{
			type: "couple",
			score: "5.0",
			photo: "/assets/images/testimonials/iulia-radu.webp",
			hu: {
				name: "Iulia I. & Radu N.",
				excerpt: "Professzionalizmusa és minőségi poénjai egy csomó nagyszerű fotót eredményezett",
				text: "Rolanddal fotózni abszolút élvezet volt. Ez volt az első profi fotózásunk, és nagyon egyszerűvé tette számunkra az egészet. Professzionalizmusa és minőségi poénjai, hogy jól érezzük magunkat, egy csomó nagyszerű eljegyzési fotót eredményezett, amelyeket örömmel fogunk újra és újra visszanézni.",
				link: "/hu/portre/iulia-radu/",
			},
			en: {
				name: "Iulia I. & Radu N.",
				excerpt: "His professionalism combined with quality jokes resulted in a bunch of great photos",
				text: "Shooting with Roland was an absolute pleasure. Even if it was our first professional photo shooting, he made it all look very easy for us. His professionalism combined with quality jokes to make us feel at ease, resulted in a bunch of great engagement shots that are worth looking at over and over again.",
				link: "/en/portraiture/iulia-radu/",
			},
		},
		{
			type: "male",
			score: "5.0",
			photo: "/assets/images/testimonials/gabor.webp",
			hu: {
				name: "B. Gábor",
				excerpt: "A képek készítése közben folyamatosan poénkodott, ami miatt az összes képemen valódi a mosoly",
				text: "Roland egy végtelenül kedves, türelmes és segítőkész ember. A fotózás elejétől kezdve nyugodt volt és igyekezett azon lenni, hogy ne stresszeljem túl a dolgokat. Kíváncsi volt az elképzeléseimre, közösen találtuk ki, hogy hol lehetne jó képeket készíteni (természetesen az ő szakértelmére hagyatkoztam leginkább, amit nem bántam meg). Beszélt arról is, hogy milyen objektíveket használ, hogy mit miért csinálunk, tippeket adott pózokhoz, így kipróbálhattam, hogy melyik kényelmes számomra. Humora nagyon ragadós, a képek készítése közben is elsütött pár poént, ami miatt az összes képemen a mosoly és nevetés valódi és egyáltalán nem erőltetett. Csak ajánlani tudom Rolandot, mert a közös munka eredménye garantált elégedettség.",
				link: "/hu/portre/gabor/",
			},
			en: {
				name: "Gábor B.",
				excerpt: "He kept cracking jokes while taking the pictures, which made the smiles in all my photos genuine",
				text: "Roland is an extremely kind, patient and helpful person. From the beginning of the photo shoot, he was calm and tried to make sure I didn't stress things too much. He was curious about my ideas; we figured out where to take good pictures together (of course, I relied mostly on his expertise, which I didn't regret). He also talked about the lenses he uses, why we do what we do, and gave tips for poses, so I could try out which ones are comfortable for me. His humor is very infectious, he cracked a few jokes even while taking the pictures, which made the smiles and laughter in all my photos genuine and not at all forced. I can only recommend Roland, because the result of working together with him is guaranteed satisfaction.",
				link: "/en/portraiture/gabor/",
			},
		},
		{
			type: "male",
			score: "",
			photo: "/assets/images/testimonials/lacko.webp",
			hu: {
				name: "A. Lackó",
				excerpt: "Ő az a fotós, akit mindenki keres",
				text: "Körülbelül 2 éve ismertem meg Rolandot. Nagyon sok fotóst kipróbáltam előtte, de mióta Rolit ismerem, évente többször is átutazom az országot, mert Ő az a fotós, akit mindenki keres. Olyan képet készít Rólad, amilyet szeretnél, nem szól bele az elképzeléseidbe, de profi tanácsokkal lát el, hogy a képeid minél profibbak legyenek. Ha úgy mész hozzá, hogy nincs elképzelésed, sincs baj, mert mindenben segítőkész, emellett emberileg is egy jószívű, vicces, és legfőképp korrekt ember, aki mellett könnyen feloldódsz, és ezáltal a fotózás is gördülékenyen zajlik. Mindenkinek ajánlani tudom Rolandot így 200+ km-ről is!",
				link: "/hu/portre/lacko-2/",
			},
			en: {
				name: "Lackó A.",
				excerpt: "He's the photographer everyone is looking for",
				text: "I met Roland about 2 years ago. I'd tried a lot of photographers before, but since I've known Roli, I travel across the country several times a year, because he's the photographer everyone is looking for. He crafts photos of you that _you_ want, he doesn't interfere with your ideas, but he provides professional advice to make your pictures as great as possible. If you don't have any ideas, no problem; he's helpful in everything, and he's also a good-hearted, funny, and above all fair person, with whom you can easily relax, and thus the photoshoot goes smoothly. I can recommend Roland to everyone even from 200+ km away!",
				link: "/en/portraiture/lacko-2/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/muskan.webp",
			hu: {
				name: "K. Muskan",
				excerpt: "Roland minden félelmemet elfeledtette velem a fotózás során",
				text: "Szégyenlős vagyok a kamera előtt, nem feltétlenül szeretem ha fotóznak. A filmes fotózásunk elég nagy kihívást jelentett számomra, de Roland minden félelmemet elfeledtette velem a fotózás során. Laza stílusú, elbűvölő személyiség, akit kiváló munkamorál jellemez; a filmes portréfotózás egész folyamata könnyednek tűnt. A folyamat során gondoskodott róla, hogy végig magabiztos legyek. Most visszatekintve az egész élményre,  határozottan azt mondom, hogy nagyon élveztem -- köszönet Rolandnak, hogy ilyen csodálatos fotós!",
				link: "/hu/portre/muskan/",
			},
			en: {
				name: "Muskan K.",
				excerpt: "Roland made me forget all of my fears during the photoshoot",
				text: "I am camera shy, I don't necessarily like being in front of the camera. Going through our film photoshoot was a bit challenging for me, but Roland made me forget all of my fears during the shoot. He has an easy-going, charming personality, and excellent work ethics; the whole process of shooting film portraits with him felt effortless. He made me feel confident and good about myself throughout the process. Now looking back to the whole experience, I'd say that I thoroughly enjoyed the experience, kudos to Roland for being such an amazing photographer.",
				link: "/en/portraiture/muskan/",
			},
		},
		{
			type: "male",
			score: "",
			photo: "/assets/images/testimonials/gyuri.webp",
			hu: {
				name: "H. György",
				excerpt: "Ha első fotózásodon gondolkodsz, de keresed a megfelelő fotóst, aki kisegít mindenben, szívből ajánlani tudom Rolandot, hihetetlen élmény lesz",
				text: "Egy ismerősömön keresztül találtam rá Rolandra, és egyből megtetszett a stílusa. Rugalmasan meg tudtuk beszélni az időpontot, én megmondtam, hogy milyen jellegű képekre és háttérre gondolok, és ő egy tökéletes helyszínt ajánlott hozzá. Ez volt az első fotózásom, így az elején nem igazán éreztem magam a bőrömben, de Roland nagyon megértő volt, mindvégig rendkívül pozitív és laza volt a hangulat, emellett több hasznos tippet adott pózolás terén. Ezeknek köszönhetően a végére már sokkal magabiztosabbnak éreztem magam, és remek képek sikerültek. Ha első fotózásodon gondolkodsz, de bizonytalan vagy a megfelelő fotós terén, aki kisegít mindenben, szívből ajánlani tudom Rolandot, hihetetlen élmény lesz.",
				link: "/hu/portre/gyuri/",
			},
			en: {
				name: "György H.",
				excerpt: "If you are thinking about your first photo shoot, but you're looking for the right photographer who will help you in everything, I can wholeheartedly recommend Roland, it will be an incredible experience",
				text: "I found Roland through an acquaintance and immediately liked his style. We were able to discuss the time flexibly, I told him what kind of pictures and background I had in mind, and he recommended just the perfect location. It was my first photoshoot, so I didn't really feel comfortable in my own skin at the beginning, but Roland was very understanding, the atmosphere was extremely positive and relaxed throughout the photoshoot, and he gave me several useful tips on posing. Thanks to these, I felt much more confident by the end, and we managed to take some incredible pictures. If you are thinking about your first photo shoot, but you are unsure about the right photographer who will help you in everything, I can wholeheartedly recommend Roland, it will be an incredible experience.",
				link: "/en/portraiture/gyuri/",
			},
		},
		{
			type: "couple",
			score: "5.0",
			photo: "/assets/images/testimonials/tatum-peter.webp",
			hu: {
				name: "Cs. Péter",
				excerpt: "Jól éreztem magam Roland kamerája előtt",
				text: "Általában kerülöm a kamerát, így egyáltalán nem vártam, hogy részt vegyek egy páros fotózáson a feleségemmel. Roland professzionalizmusa és szakértelme azonban sokat segített a fotózásban. Hamar jól éreztem magam a kamera előtt, és a várakozásomat felülmúlta az egész élmény. Összességében a fotózás nagyon romantikus volt, és örökre megőrzöm ezeket a csodás emlékeket a feleségemmel.",
				link: "/hu/portre/tatum-peter/",
			},
			en: {
				name: "Péter Cs.",
				excerpt: "I felt comfortable in front of Roland's camera",
				text: "As someone who typically avoids the camera, I was not looking forward to participating in a couples shoot with my wife. However, Roland's professionalism and artistic understanding for composition helped guide the photoshoot. I felt comfortable in front of the camera and my expectations were exceeded for the entire experience. Overall, the photoshoot was quite romantic and I look forward to cherishing these forever memories with my wife.",
				link: "/en/portraiture/tatum-peter/",
			},
		},
		{
			type: "male",
			score: "5.0",
			photo: "/assets/images/testimonials/adam.webp",
			hu: {
				name: "H. Ádám",
				excerpt: "Ha ez lesz az első portréfotózásod, feltétlenül ajánlom Rolandot, hiszen mindenben türelmesen segít",
				text: "Egy ideje követtem Roland munkásságát, és igazán tetszettek a portrék, amiket készített másokról, ezért megbeszéltünk egy fotózást. Nagyon rugalmas az időpontegyeztésben, így könnyű dolgod lesz vele. Illetve, ha ez lesz az első portréfotózásod, mint nekem, feltétlenül ajánlom Rolandot, hiszen mindenben türelmesen segített és a koncepciót is együtt találtuk ki. A fentieknek köszönhetően nagyon pozitív élmény volt számomra a fotózás, amit ezúton is köszönök mégegyszer!",
				link: "/hu/portre/adam-3/",
			},
			en: {
				name: "Ádám H.",
				excerpt: "If this is your first portrait shoot, I definitely recommend Roland, as he patiently helped with everything",
				text: "I've been following Roland's work for a while and I really liked the portraits he made of others, so we arranged a photo shoot. He is very flexible in scheduling, so it will be easy for you to work with him. And, if this is your first portrait shoot, like me, I definitely recommend Roland, as he patiently helped with everything and we came up with the concept together. Thanks to the above, the photo shoot was a very positive experience for me, for which I would like to thank Roland once again!",
				link: "/en/portraiture/adam-3/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/tatum.webp",
			hu: {
				name: "Cs. Tatum",
				excerpt: "Az első képünk pillanatától kezdve kényelmesnek éreztem a fotózást, nagyon jól ment a kommunikáció",
				text: "Nemrég elhatároztam, hogy kilépek a komfortzónámból. Változásra vágytam. Évekig követtem Rolandot az Instagramon, és egy nap szeszélyből üzentem neki, hogy találkozzunk egy fotózáson. Íme az igazi csapás: Utálok kamera előtt állni. Úgy döntöttem, teljes mértékben elkötelezem magam amellett, hogy a kilépjek komfortzónámból. Az első képünk pillanatától kezdve kényelmesnek éreztem a fotózást, nagyon jól ment a kommunikáció. A fotózás során Roland irányított a pózolásban, és ragaszkodott ahhoz, hogy a lehető legkényelmesebbé tegye a dolgokat. A fotózás végére mély beszélgetésbe merültünk az önelégültség harcáról. A növekedéshez le kell győznünk a tökéletesség iránti vágyunkat, és fel kell ölelnünk azokat a területeket, ahol gyengék vagyunk. Aki fontolgatja, nagyon ajánlom, hogy tegye meg ezt a lépést, és foglaljon le egy fotózást Rolanddal. Ne feledd, nem tudsz fejlődni, ha a komfortzónádban maradsz.",
				link: "/hu/portre/tatum/",
			},
			en: {
				name: "Tatum Cs.",
				excerpt: "From the moment of our first picture, I felt comfortable with our ability to communicate",
				text: "Recently I became determined to push myself out of my comfort zone. I desired change. I followed Roland for several years on Instagram and messaged him on a whim to meet up for a photoshoot. Here is the real catch, I HATE standing in front of a camera. I decided I was fully committing to my leap outside of my comfort zone. From the moment of our first picture, I felt comfortable with our ability to communicate. Throughout the shoot, Roland guided me in posing and insisted on making things as comfortable as possible. By the end of the shoot, we delved into a deep conversation about fighting the battle of complacency. To grow, we must overcome our desire for perfection and embrace the areas where we are weak. For anyone considering it, I highly recommend taking that leap and booking a photoshoot with Roland. Remember, you cannot grow if you remain in your comfort zone.",
				link: "/en/portraiture/tatum/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/lilla.webp",
			hu: {
				name: "B. Lilla",
				excerpt: "Rolanddal a fotózások mindig iszonyat jó hangulatban telnek, egy percig nem érzi feszélyezve magát az ember",
				text: "Roland munkája a social medián jött velem szembe. Rögtön be is követtem a zseniális hangulatú, minőségű képeit miatt. Az első közös fotózásunkon vált számomra világossá, hogy nem csak egy nagyszerű fotóst, de egy nagyon jó fej embert ismerhetek meg a személyében. Rolanddal a fotózások mindig iszonyat jó hangulatban telnek, egy percig nem érzi feszélyezve magát az ember. Még akkor sem, ha épp nem szokott a kamera előtt állni, avagy a kamera másik oldalához van szokva. Kreativitása motiváló, segítőkészsége pedig a mai világban ritka. Bármikor beszélek Vele, mindig szívesen ellát hasznos tanácsokkal, bátorít és ösztönöz. Teljes szívemből ajánlom Rolandot, egy élmény vele dolgozni!",
				link: "/hu/portre/lilla-2/",
			},
			en: {
				name: "Lilla B.",
				excerpt: "The photoshoots with Roland always happen in a very good mood, you don't feel tense for a minute",
				text: "I came across Roland's work on social media. I immediately started following him because of his brilliant, high-quality pictures. During our first photo shoot together, it became clear to me that I got to know not only a great photographer, but also a very kind person. The photoshoots with Roland always happen in a very good mood, you don't feel tense for a minute. Not even if you are not used to standing in front of the camera, or if you are used to the other side of the camera. His creativity is motivating and his willingness to help is rare in today's world. Whenever I talk to him, he is always happy to provide me with useful advice, motivation and encouragement. I wholeheartedly recommend Roland, working with him is a delightful experience!",
				link: "/en/portraiture/lilla-2/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/eszter-3.webp",
			hu: {
				name: "Sz. Eszter",
				excerpt: "Bátran ajánlom őt azoknak, akik szeretnének olyan képeket magukról, amiken tényleg a legjobb oldaluk köszön vissza",
				text: "Amikor Rolanddal először fotózni mentem, kicsit tartottam az egésztől; nem vagyok hozzászokva, hogy más fotóz engem. Nagyon könnyű volt vele megtalálni a közös hangot, nem kellett feszengenem, és ami leginkább segített, hogy nyitott volt az én preferenciáimra, valóban partnerként kezelt a fotózás, ötletelés, és az elkészült képek kiválasztása során. Azóta már többször is fotóztunk együtt, és bátran ajánlom őt azoknak, akik szeretnének olyan képeket magukról, amiken tényleg a legjobb oldaluk köszön vissza!",
				link: "/hu/portre/eszter-7/",
			},
			en: {
				name: "Eszter Sz.",
				excerpt: "I strongly recommend him to those who want pictures of themselves that really reflect their best side",
				text: "When I went to take photos with Roland for the first time, I was a little afraid of it all; I'm not used to someone else taking pictures of me. It was very easy to find common ground with him, I didn't have to strain, and what helped me the most was that he was open to my preferences. He really treated me as an equal partner during the brainstorming, photography, and final selection process. Since then, we have taken photos together several times, and I strongly recommend him to those who want pictures of themselves that really reflect their best side!",
				link: "/en/portraiture/eszter-7/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/kata-mira.webp",
			hu: {
				name: "N. Kata",
				excerpt: "A sok poénjával könnyen oldotta a hangulatot, így egyből az igazi mosolyom bújt elő, és szenzációs képeink születtek",
				text: "Életem során rengeteget izgultam, féltem kiállni emberek elé és nehezen tudtam őszintén mosolyogni. Egyik nap szembe jött velem Roli fotós oldala, és nagyon szimpatikus volt ő maga is és a képei is. Nagyon örültem, hogy gyorsan válaszolt, és még azon a héten el is tudtunk menni fotózni. Nagyon izgultam az elején, mert azt hittem, hogy rólam nem lehet jó fotót csinálni, de ő mégis tudott. A sok poénjával könnyen oldotta a hangulatot, így egyből az igazi mosolyom bújt elő, és szenzációs képeink születtek. Mindenkinek ajánlani tudom, Roland remek társaság, aki csodás képeket, emlékeket készít. Már sokszor voltam vele portré fotózni egyéniben és párosban is, és vele minden alkalom egy feltöltődés.",
				link: "/hu/portre/kata-mira-2/",
			},
			en: {
				name: "Kata N.",
				excerpt: "He quickly created comfort with his many jokes, so my real smile immediately appeared, and we achieved some sensational portraits",
				text: "Throughout my life, I was nervous a lot, I was afraid to stand in front of people and it was difficult for me to smile sincerely. One day I came across Roli's photography page, and he himself and his pictures were very nice. I was very happy that he responded quickly and we were even able to go for a portrait shoot that week. I was very nervous at the beginning, because I thought it was impossible to take a good photo of me, but he was easily able to mane great photos. He quickly created comfort with his many jokes, so my real smile immediately appeared, and we achieved some sensational portraits. I can recommend him to everyone, Roland is a great company who creates wonderful pictures and memories. I have taken portrait photos with him many times already, both individually and as a couple, and every time with him is a recharge.",
				link: "/en/portraiture/kata-mira-2/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/mici.webp",
			hu: {
				name: "G. Mici",
				excerpt: "A fotózás alatt gondoskodott az oldott hangulatról, könnyen meg tudtuk találni a közös hangot, és tökéletesen el tudta találni az elképzelésemet",
				text: "Rolanddal pár hónappal ezelőtt sodort össze minket az élet, amikor egy kellemes tavaszi délutánon váratlanul odalépett hozzánk, hogy a távolból csinált rólunk a barátnőmmel pár fotót. Teljesen el voltunk ragadtatva, szuper képek lettek! Látva a további munkáit, biztos voltam benne, ha minőségi fotókra lesz szükségem, még keresni fogom. Hamarosan így is lett, és abszolút beváltotta a hozzá fűzött reményeimet. A fotózás alatt gondoskodott az oldott hangulatról, könnyen meg tudtuk találni a közös hangot, és tökéletesen el tudta találni az elképzelésemet. Kifejezetten elégedett voltam a rugalmasságával és gyorsaságával az időpont egyeztetés, maga a fotózás és a megkapott képek tekintetében is. Csak ajánlani tudom Rolandot mindenkinek! És ahogy meglátja, használja a fényt… na azt tedd próbára!",
				link: "/hu/portre/mici/",
			},
			en: {
				name: "Mici G.",
				excerpt: "During the photo shoot, he ensured a very relaxed atmosphere, we could easily find common ground, and he was able to perfectly capture my ideas",
				text: "Life brought Roland and I together a few months ago, when he approached us unexpectedly on a pleasant spring afternoon to take a few photos of me and my girlfriend from afar. We were completely delighted, the pictures turned out great! After seeing his other work, I was sure that if I needed quality photos, I would go to him. It soon became so, and it absolutely lived up to my expectations! During the photo shoot, he ensured a very relaxed atmosphere, we could easily find common ground, and he was able to perfectly capture my ideas. I was particularly satisfied with his flexibility and speed in terms of scheduling the appointment, the photography itself, and the images I received. I can only recommend Roland to everyone! And as soon as you see him using the light… well, you should really see him!",
				link: "/en/portraiture/mici/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/detti.webp",
			hu: {
				name: "O. Detti",
				excerpt: "Kedves, türelmes, és a fotózás teljes időtartalma alatt igyekszik az önfeledt légkör megteremtésére",
				text: "Immár másodszor volt szerencsém Rolanddal együtt dolgozni. Bevallom, meglepett, amikor pár hónappal ezelőtt az utcán egy spontán fotózásra szólított le. Sosem tartottam fotogénnek magam, meggyőződésem volt, hogy rólam szinte lehetetlen előnyös képet készíteni. Ezzel ellentétben, erre mindkét alkalom tökéletesen rácáfolt. A fotózások remek hangulatban teltek, a végeredményért pedig egyszerűen oda és vissza vagyok. Fontosnak tartom még megemlíteni Roland személyét; kedves, türelmes, és a fotózás teljes időtartalma alatt igyekszik az önfeledt légkör megteremtésére. Aki egy kis önbizalom növelésre, jó hangulatra, és persze csoda képekre vágyik, annak szívből tudom ajánlani Őt!",
				link: "/hu/portre/detti/",
			},
			en: {
				name: "Detti O.",
				excerpt: "He is kind, patient, and always creates an intimate atmosphere during the entire duration of the photo shoot",
				text: "It's been the second time I had the pleasure of working with Roland. I admit, I was surprised when he invited me to a spontaneous photo shoot on the street a few months ago. I never considered myself photogenic, I was convinced that it was almost impossible to take a favorable picture of me. On the contrary, it was completely refuted on both occasions. The photoshoots were in a great atmosphere, and I am simply there and back for the end result. I also consider it important to mention the person of Roland; he is kind, patient, and always creates an intimate atmosphere during the entire duration of the photo shoot. I can wholeheartedly recommend him to anyone who wants a little self-confidence boost, a good mood, and of course wonderful pictures!",
				link: "/en/portraiture/detti/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/eszter-2.webp",
			hu: {
				name: "Sz. Eszter",
				excerpt: "Az egész fotózás pörgős volt, az ötletek egymást követték, a hideg és a szél pedig háttérbe szorultak",
				text: "Mindig is nagyon szerettem mosolyogva a kamera előtt állni, ezért kifejezetten megörültem ennek a nem mindennapi, kreatív fényfestős fotózásnak. Az egész fotózás pörgős volt, az ötletek egymást követték, a hideg és a szél pedig háttérbe szorultak. A kötetlen ötletelés Rolanddal a fotózás előtt pedig még jobban feldobta a hangulatot. Ilyen kreatív és különleges fotózáson még soha nem vettem részt, úgyhogy nagyon érdekes és inspiráló új élményekkel - és persze csodálatos képekkel - gazdagodhattam. A fotózás egyszerre volt vagány és elegáns, ezért bátran ajánlom mindenkinek, aki kedvet érez, hogy megmutassa a benne lévő kreativitást. Remélem, hogy lesz még lehetőségem hasonló fantáziadús projektben részt venni!",
				link: "/hu/portre/eszter-5/",
			},
			en: {
				name: "Eszter Sz.",
				excerpt: "The entire photo shoot was fast-paced, ideas followed ideas, and the cold and the wind took a back seat",
				text: "I've always loved standing in front of the camera with a smile, so I was particularly pleased with this unusual, creative photo shoot with light painting. The entire photo shoot was fast-paced, ideas followed ideas, and the cold and the wind took a back seat. The informal brainstorming with Roland before the photoshoot lifted the mood even more. I have never participated in such a creative and special photo shoot before, so I was able to enrich myself with very interesting and inspiring new experiences - and of course wonderful pictures. The photoshoot was edgy and elegant at the same time, so I strongly recommend it to anyone who feels like showing their creativity. I hope that I will have the opportunity to participate in a similar creative project in the future!",
				link: "/en/portraiture/eszter-5/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/eszter.webp",
			hu: {
				name: "B. Eszter",
				excerpt: "Összeségében nagyon élveztem a fotózást Rolanddal, tökéletes első alkalom volt",
				text: "Én mindig is izgulós típus voltam, ez a fotózás előtt sem volt másképp. Sosem voltam még fotózáson, nem tudtam, milyen lesz a közös munka, hogy hogyan kéne beállnom a képekhez, vagy hogy mennyire fogom tudni elengedni magam. De ez az izgulás az első percek után elmúlt. Nagyok jól esett, hogy beszélgetünk előtte, kicsit ráhangolódtunk fotózásra és közösen találtuk meg a legjobb helyeket. Nagyon jól esett a sok biztatás és dicséret, illetve Roland viccei is jók voltak, ami sokat segített, hogy őszintén tudjak mosolyogni! Ilyen sok jó kép sosem készült még rólam, és alig vártam, hogy megkapjam őket. Összeségében én nagyon élveztem a fotózást Rolanddal, tökéletes első alkalom volt, és remélem lesz lehetőségem még hasonlókhoz!",
				link: "/hu/portre/eszter-4/",
			},
			en: {
				name: "Eszter B.",
				excerpt: "All in all, I very much enjoyed the photo shoot, it was a perfect first-time experience",
				text: "I have always been the anxious type, and this was no different before the photo shoot with Roland. I had never been on a shoot before, I didn't know what the joint work would be like, how I should pose for the pictures, or how much I would be able to let myself go. But this excitement passed after the first few minutes. It was great to talk for a few minutes before we got into the shoot, so I could settle in for the occasion better. I felt very comfortable with Roland's encouragement along the way, and his jokes were also good, which helped me a lot to be able to smile honestly! I've never had so many good pictures taken of me before, and I couldn't wait to get them. All in all, I very much enjoyed the photo shoot, it was a perfect first-time experience, and I hope I will have the opportunity to do more like this!",
				link: "/en/portraiture/eszter-4/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/gabcsi.webp",
			hu: {
				name: "V. Gabcsi",
				excerpt: "Ez volt az első alkalom, amikor a leghamarabb feloldódtam fotózás során",
				text: "A fotózás előtt kissé féltem, hogy jól fognak-e sikerülni a fotók, mivel nincs modellkedésben sok tapasztalatom és eddig csak ismerősök és barátok fotóztak. Kimozdultam a komfort zónámból ezen az alkalmon, ugyanakkor maga a stílus (vintage, retro) nagyon is közel állt hozzám, így mégis otthonosnak éreztem fotózást. Talán ez volt az első alkalom, amikor a leghamarabb feloldódtam fotózás során. Örültem, hogy kíváncsi volt Roli a véleményemre, megmutatta a fotókat, érdekelte, hogy van-e bármilyen elképzelésem, akár helyszínnel kapcsolatban, akár pózokról legyen szó. Tetszett, hogy együtt dolgoztunk azon, hogy minőségi és csodálatos képek szülessenek, és nem éreztem azt, hogy egyedül kéne megbirkóznom a feladattal. Összességében elmondhatom, hogy Roli nagyon minőségi és kreatív munkát végez a fotózás és az utómunka során!",
				link: "/hu/portre/gabcsi/",
			},
			en: {
				name: "Gabcsi V.",
				excerpt: "This was the first time I could relax the quickest during a photo shoot",
				text: "Before the photo shoot, I was a little afraid of whether the photos would turn out well, since I don't have much experience in modeling and so far only friends and acquaintances have taken photos of me. I moved out of my comfort zone on this occasion, but at the same time the style itself (vintage, retro) was very close to me, so I still felt comfortable taking photos. This was perhaps the first time I had the earliest time to dissolve during a photo shoot. I was glad that Roli was interested in my opinion, he showed me the photos, he was interested in whether I had any ideas about the location or posing. I liked that we worked together to create these wonderful images, and I didn't feel like I had to cope with the task alone. Overall, I can say that Roli does a very high-quality and creative job during the photography and post-production!",
				link: "/en/portraiture/gabcsi/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/reka.webp",
			hu: {
				name: "T. Réka",
				excerpt: "Azonnal meg tudtam nyílni, hiszen egy rendkívül biztonságos és kellemes légkört teremtett már az első pillanattól kezdve",
				text: "Rolanddal először a karácsonyi vásárban vettem részt fotózáson, ami gyorsan egy rendkívül jó hangulatú baráti beszélgetéssé alakult. Szinte azonnal meg tudtam nyílni, hiszen csupán a lényével is egy rendkívül biztonságos és kellemes légkört teremtett már az első pillanattól kezdve. Minden gátlásomat elengedve tudtam a kamerába mosolyogni, ami előtte nem volt jellemző rám, de Rolandnak hála, ezt az oldalamat is meg tudtam ismerni. Azóta kétszer volt alkalmam közös fotózáson részt venni vele, amik szintén nagyon flottul mentek, a kézhez kapott képeim után pedig a rég elveszett önbizalmam is elkezdett visszatérni, Rolandnak hála!",
				link: "/hu/portre/reka-borbala-2/",
			},
			en: {
				name: "Réka T.",
				excerpt: "I was able to open up almost immediately, as he created an extremely safe and pleasant atmosphere from the very first moment",
				text: "I took part in a photo shoot with Roland for the first time at the Christmas market, which quickly turned into a friendly conversation with an extremely good atmosphere. I was able to open up almost immediately, as he created an extremely safe and pleasant atmosphere from the very first moment. Letting go of all my inhibitions, I could smile at the camera, which was not characteristic of me before, but thanks to Roland, I was able to get to know this side of myself as well. Since then, I've had the opportunity to take part in a joint photo shoot with him twice, both of which also went very smoothly, and after the pictures I received, my long-lost self-confidence started to return, thanks to Roland!",
				link: "/en/portraiture/reka-borbala-2/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/greti.webp",
			hu: {
				name: "A. Gréta",
				excerpt: "Nem számítottam arra, hogy mekkora magabiztosságot és önbizalmat ad majd a fotózás Rolanddal",
				text: "Elég sokszor vannak gátlásaim, ha más készít rólam képeket, ezért kicsit aggódtam, hogy egyáltalán komfortosnak érzem-e majd az egész folyamatot és tetszeni fognak-e a képek. Nos, azt kell mondjam, hogy teljesen pozitív csalódás volt számomra. Abban biztos voltam, hogy hihetetlen élmény lesz, mert ez volt az első igazi nagybetűsnek mondható fotózásom, de arra nem számítottam, hogy mekkora magabiztosságot és önbizalmat ad majd a fotózás Rolanddal. Egyszerűen minden kép, amit kaptam, csodálatos volt, és elkapott a bőség zavara, hogy mennyire gyönyörűek egytől egyig. A hangulat végig szuper volt, sok nevetéssel, mindezt profizmussal ötvözve.",
				link: "/hu/portre/greti/",
			},
			en: {
				name: "Gréta A.",
				excerpt: "I didn't expect how much self-confidence shooting with Roland would give me",
				text: "I often have inhibitions when someone takes my photo, so I was a little worried about whether I would feel comfortable with the whole process and whether I would like the pictures. Well, I have to say that it was a completely positive disappointment for me. I was sure it would be an incredible experience because it was my first proper photo shoot, but I didn't expect how much self-confidence shooting with Roland would give me. Every picture I received was amazing; I was overwhelmed by how beautiful each one was. The atmosphere was great throughout the photoshoot, with lots of laughter, all combined with professionalism.",
				link: "/en/portraiture/greti/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/jazmin.webp",
			hu: {
				name: "V. Jázmin",
				excerpt: "Roland humorának köszönhetően az első pillanattól kezdve megfeledkeztem arról, hogy egyáltalán fotózáson vagyok",
				text: "Eddig kétszer volt alkalmam együtt dolgozni Rolanddal, és mindkét alkalom felejthetetlen élmény volt. Az első alkalommal nem tudtam mire számítsak, azt meg főleg nem, hogy hogyan kell \"pózolni\" a kamera előtt. Viszont Roland humorának köszönhetően az első pillanattól kezdve megfeledkeztem arról, hogy egyáltalán fotózáson vagyok! Amikor a párommal mentünk hozzá, féltünk, hogy furcsa lesz kamera előtt csókot váltani, de ott is végig humorizált, kihozta belőlünk a természetes, meghitt pillanatainkat. Ezáltal a fotók nem beállított pillanatokat, hanem valódi szeretetet sugároznak, amikre mindig mosolyogva nézünk. Röviden, ha valakit, Rolandot csakis ajánlani tudom!",
				link: "/hu/portre/jazmin/",
			},
			en: {
				name: "Jázmin V.",
				excerpt: "Thanks to Roland's humor, I forgot that I was at a photo shoot from the very first moment",
				text: "I have had the opportunity to work with Roland twice so far, and both times were unforgettable experiences. The first time I didn't know what to expect, especially not how to pose in front of the camera. However, thanks to Roland's humor, I forgot that I was at a photo shoot from the very first moment! When my partner and I went to see him, we were afraid that it would be strange to kiss in front of the camera, but even there he was humorous throughout, bringing out our natural, intimate moments. As a result, the photos don't show posed moments but radiate real love, which we always look at with a smile. In short, I can only recommend Roland!",
				link: "/en/portraiture/jazmin/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/kincso.webp",
			hu: {
				name: "Z. Kincső",
				excerpt: "A legjobb fotózás volt az életemben",
				text: "A legjobb fotózás volt az életemben! Egy olyan témában készültek a képek, ami tényleg én vagyok. Roland vicces, kedves személyisége garantálta a jó hangulatot. Jól éreztem magam és felszabadultam. Lenyűgözött ahogy készíti képeit, azzal a precizitással, pontossággal, az elképzelésekkel és ötletekkel a fejében. Nekem nagyon tetszik a végeredmény. Köszönöm! Szívből ajánlom mindenkinek Rolandot! Csodás, amit alkot a világban!",
				link: "/hu/portre/kincso/",
			},
			en: {
				name: "Kincső Z.",
				excerpt: "It was the best photo shoot of my life",
				text: "It was the best photo shoot of my life! We took photos on a topic that is really me. Roland's funny, kind personality guaranteed a good atmosphere. I felt good and liberated. I was impressed by the way he creates his pictures, with the precision, accuracy, the visions and ideas in his head. I really like the end result. Thanks! I wholeheartedly recommend Roland to everyone! It's amazing what he's doing in the world!",
				link: "/en/portraiture/kincso/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/saci.webp",
			hu: {
				name: "U. Sarolta",
				excerpt: "Egy teljesen új arcomat mutatta meg, amiért nagyon hálás vagyok",
				text: "Életem első fotózására készültem. Megmondom őszintén, nagyon izgultam, mert a kamerák előtt sosem érzem komfortosan magam, pedig edzőként igazán nincs mit takargatnom. Rolandot sem ismertem, ez sem könnyített a helyzeten. Hála Istennek, Rolanddal a közös munka minden várakozásomat felülmúlta, teljesen sikerült feloldódni már a fotózás legelején. Nagyon meg vagyok elégedve a képekkel, egy teljesen új arcomat mutatta meg, amiért nagyon hálás vagyok. Ha épp egy laza, kedves, jó humorú fotóst keresnél, akivel hamar megtalálod a közös hangot, szívből ajánlom Rolandot! Köszönöm ezúton is a lehetőséget, a képeket, szuper emlék és ajándék is egyben!",
				link: "/hu/portre/saci/",
			},
			en: {
				name: "Sarolta U.",
				excerpt: "He was able to show me a completely new face of mine, for which I am very grateful",
				text: "I was preparing for my first photo shoot. To be honest, I was very nervous because I never feel comfortable in front of the cameras, even though as a coach I really have nothing to hide. I didn't know Roland either, and that didn't make the situation any easier either. Thank God, working with Roland exceeded all my expectations, I managed to completely relax from the very beginning of the photo shoot. I am very satisfied with the pictures; Roland was able to show me a completely new face of mine, for which I am very grateful. If you're looking for a relaxed, nice, good-humored photographer with whom you'll quickly find common ground, I wholeheartedly recommend Roland! Thank you again for the opportunity, the pictures, and a great memory and gift at the same time!",
				link: "/en/portraiture/saci/",
			},
		},
		{
			type: "couple",
			score: "",
			photo: "/assets/images/testimonials/jackeline-andre.webp",
			hu: {
				name: "Jackie N. & André P.",
				excerpt: "Roland nagyon barátságos volt, sokat beszélgettünk és nevettünk, így könnyen feloldódtunk és hihetetlen jó képek készültek rólunk",
				text: "Az első közös fotózásunkhoz kerestem Budapesti portré fotóst Instagramon, ekkor találtam rá Rolandra. A kezdetektől nagyon tetszett a munkája; a képei, a színek, mind passzoltak az elvárásainknak. A fotózás elején kicsit félénkek voltunk, de Roland nagyon barátságos volt, sokat beszélgettünk és nevettünk, így könnyen feloldódtunk és hihetetlen jó képek készültek rólunk. Budapest nagyon sokat jelent nekünk, és Roland kitűnően megörökítette a közös élményünket.",
				link: "/hu/portre/jackeline-andre/",
			},
			en: {
				name: "Jackie N. & André P.",
				excerpt: "Roland was very friendly, we talked and laughed a lot, so we got along easily, and we got incredibly good pictures",
				text: "I was looking for a Budapest portrait photographer on Instagram for our first photo shoot together, and that's when I found Roland. I really liked his work from the beginning; the pictures, colors, and everything matched our expectations. At the beginning of the photoshoot, we were a bit shy, but Roland was very friendly, we talked and laughed a lot, so we got along easily, and we got incredibly good pictures. Budapest means a lot to us, and Roland perfectly captured our shared experience.",
				link: "/en/portraiture/jackeline-andre/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/nori.webp",
			hu: {
				name: "V. Nóri",
				excerpt: "Sikerült elérnie, hogy feloldódjak, folyamatosan instruált, a végeredmény pedig gyönyörű lett",
				text: "Őszintén szólva, nem vagyok az a mosolygós fajta. Ráadásul, gyerekkorom óta kényelmetlenül éreztem magam, ha célba vett egy fényképezőgép objektíve. Ezt pedig csak tetézte a készülék túloldaláról érkező kissé ingerült felszólítás: 'Mosolyogj már egy kicsit!'. Szerencsére, ahogy teltek az évek, a kamera előtti szorongás is mérséklődött. Az igazi áttörést azonban Rolandnak köszönhetem. Már az első fotózásunk alkalmával sikerült elérnie, hogy feloldódjak, folyamatosan instruált, a végeredmény pedig gyönyörű lett. Már alig várom, hogy újra együtt alkothassunk valami szépet, a kalapjaimmal a főszerepben!",
				link: "/hu/portre/nori-2/",
			},
			en: {
				name: "Nóri V.",
				excerpt: "He managed to get me to relax, he kept instructing me, and the results are beautiful",
				text: "Honestly, I'm not the smiling type. Also, ever since I was a kid, I've been uncomfortable being held up by a camera lens. And this was only compounded by the slightly irritated request from the other side of the device: 'Smile a little!' Fortunately, as the years went by, the anxiety in front of the camera lessened. However, I owe the real breakthrough to Roland. Already during our first photo shoot, he managed to get me to relax, he kept instructing me, and the results are beautiful. I can't wait to create something beautiful together again, starring my hats!",
				link: "/en/portraiture/nori-2/",
			},
		},
		{
			type: "male",
			score: "",
			photo: "/assets/images/testimonials/balazs.webp",
			hu: {
				name: "B. Balázs",
				excerpt: "Nem volt nyomás, nem volt stressz",
				text: "Roppantul izgultam Roland portré fotózása előtt, mert azelőtt nem vettem részt hasonló eseményen. Az volt a legrémisztőbb, hogy a zöldfülűségem kényelmetlen szituációkhoz fog vezetni, és égni fogok, hogy a legtriviálisabb pózolási axiómákat sem ismerem. Ezek az aggályok azonnal elpárologtak, amint kezet fogtam a mosolygós és barátságos úriemberrel. Találkozásunk pillanatától egy haverral lógtam, viccelődtem és közben mindenféle képeken ötleteltünk. Nem volt nyomás, nem volt stressz. Meglepetésemre a fotók rendkívül szépen sikerültek, a kora őszi színek remekül mutatnak a képeken! Nem csak, hogy minden pózolási aggályomon túllendültem, de egy teljesen új lencsén keresztül láttam magamat. Érdekes élmény volt kívülről tekinteni a mozdulatokra, gesztikulációkra és érzelmekre. Ezért Rolandnak hálával tartozom.",
				link: "/hu/portre/balazs/",
			},
			en: {
				name: "Balázs B.",
				excerpt: "There was no pressure, no stress",
				text: "I was very nervous before Roland's portrait photography session because I had never participated in a similar event before. The scariest thing was that my inadequate posing skills would lead to uncomfortable situations. Those concerns evaporated as soon as I shook hands with the smiling and friendly gentleman. From the moment we met, I hung out with a friend, joked, and we brainstormed all kinds of photo ideas together. There was no pressure, no stress. To my surprise, the photos turned out extremely well, the early autumn colors look beautiful! Not only did I overcome all of my posing concerns, but I saw myself through a whole new lens. It was an interesting experience to look at the movements, gestures, and emotions from the outside. I owe Roland a debt of gratitude for that.",
				link: "/en/portraiture/balazs/",
			},
		},
		{
			type: "couple",
			score: "",
			photo: "/assets/images/testimonials/cinta-jorge.webp",
			hu: {
				name: "Cinta W. & Jorge G.",
				excerpt: "Nagyon izgultunk az elején, de Roland, nagyszerű személyiség és szakember lévén, segített végig nyugodtnak maradni",
				text: "Rolandot a Budapesti nyaralásunkon ismertük meg, amikor megmutatott nekünk egy fotót, amit spontán készített rólunk az utcán. A munkái alapján nagyszerű szakembernek gondoltuk, így felkértük életünk első közös fotózására. A fotózás nagyszerű hangulatban, élménydúsan telt. Nagyon izgultunk az elején, de Roland, nagyszerű személyiség és szakember lévén, segített végig nyugodtnak maradni. A lényeg az, hogy legyél önmagad a fotózáson, hogy a képek visszaadják a valódi önmagadat. Kérdés nélkül egy felejthetetlen élmény volt!",
				link: "/hu/portre/cinta-jorge/",
			},
			en: {
				name: "Cinta W. & Jorge G.",
				excerpt: "We were nervous, but since Roland is a very open and friendly photographer, he helped us feel very comfortable at all times",
				text: "We met Roland on our trip to Budapest, when he showed us the photograph he had taken of us unaware. We saw that he was a great professional, and later we contacted him to do our first photo session. The shooting was very dynamic and fun. We were nervous, but since Roland is a very open and friendly photographer, he helped us feel very comfortable at all times. In the end, the important thing was to be yourself during the session to come out as naturally as possible. Without a doubt, an unforgettable experience!",
				link: "/en/portraiture/cinta-jorge/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/anna.webp",
			hu: {
				name: "M. Anna",
				excerpt: "Teljesen érthető és követhető instrukciókat adott, valamint segített, hogy az általam elképzelt képek tényleg olyanok legyenek, ahogy azt megálmodtam",
				text: "Tökéletesek! Egytől egyig. Amikor utaztam a fotózás helyszínére, azon gondolkodtam, hogy szerintem 4-5 kép bőven elég lesz, végtére is, minek több? Nos, abból a több, mint 200 (Roland által örömmel és dalolva készített) képből alig tudtam választani. Mindig megtalálta a jó szögeket, helyeket és kifejezetten nyitott volt az én ötleteimre is végig. Teljesen érthető és követhető instrukciókat adott, valamint segített, hogy az általam elképzelt képek tényleg olyanok legyenek, ahogy azt megálmodtam.",
				link: "/hu/portre/anna-5/",
			},
			en: {
				name: "Anna M.",
				excerpt: "Roland gave fully comprehensible and easy-to-follow instructions and helped me to make sure that the images came to life exactly as I envisioned them",
				text: "They are perfect! All of them. When I traveled to the location of the photo shoot, I thought that I think 4-5 pictures will be enough, after all, why more? Well, I could hardly choose from more than 200 pictures (made by Roland with joy and singing). He always found the right angles and places and was particularly open to my ideas throughout. Roland gave fully comprehensible and easy-to-follow instructions and helped me to make sure that the images came to life exactly as I envisioned them.",
				link: "/en/portraiture/anna-5/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/cinti.webp",
			hu: {
				name: "M. Cinti",
				excerpt: "Nagyon közvetlenül telt a fotózás Rolanddal már az első perctől kezdve",
				text: "Nagyon közvetlenül telt a fotózás Rolanddal már az első perctől kezdve. Ez volt az első fotózásom, így ez nagyon sokat segített nekem abban, hogy hamar feloldódhassak. Idejét és türelmét nem sajnálva készültek el a változatos tematikájú képek. Sokat segített a megfelelő pózokban, és mindig meghallgatta az elképzeléseim... a végeredmény pedig nagyszerű lett!",
				link: "/hu/portre/cinti/",
			},
			en: {
				name: "Cinti M.",
				excerpt: "The photoshoot with Roland was very direct from the first minute",
				text: "The photoshoot with Roland was very direct from the first minute. It was my first shoot, so it helped me a lot to relax. He put in his best effort to create a diverse range of photos that I was very happy with. He helped me a lot with the right poses and always listened to my ideas... and the results turned out stunning!",
				link: "/en/portraiture/cinti/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/dori.webp",
			hu: {
				name: "E. Dóri",
				excerpt: "A gyönyörű képek mellé pedig grátiszként egy végtelenül jó fej és vicces fotóst is kapsz",
				text: "Ismered azt az érzést, hogy rólad nem lehet jó képet csinálni? Én ezzel a mondattal indultam el fotózni Rolanddal, aki ezt követően a végtelen türelmével, szuper látásmódjával és kreativitásával bebizonyította, hogy nincs igazam, én pedig nem győztem utána válogatni a jobbnál jobb képek közül. A gyönyörű képek mellé pedig grátiszként egy végtelenül jó fej és vicces fotóst is kapsz.",
				link: "/hu/portre/dori/",
			},
			en: {
				name: "Dóri E.",
				excerpt: "In addition to the beautiful pictures, you also get an extremely good-natured and funny photographer to work with",
				text: "Do you know that feeling that you can't take a good picture of yourself? I set off with this exact sentence in mind for my photo shoot with Roland, who then proved me wrong with his endless patience, superb vision, and creativity. After the photo shoot I got so many great photos to choose from that it was actually difficult to select my favorite ones. In addition to the beautiful pictures, you also get an extremely good-natured and funny photographer to work with.",
				link: "/en/portraiture/dori/",
			},
		},
		{
			type: "couple",
			score: "",
			photo: "/assets/images/testimonials/luca-david.webp",
			hu: {
				name: "P. Luca & P. Dávid",
				excerpt: "Nem csak figyelmes, de maximálisan professzionális (és nem mellesleg a humorérzéke is páratlan)",
				text: "Rolanddal egyszerűen fantasztikus volt a fotózás. Nagyon kedves, segítőkész és igyekszik a legkreatívabban megörökíteni a pillanatokat. Mindenkinek boldogan ajánlom. Garantálom, hogy nem mindennapi élményben lesz részetek, ha Őt választjátok. Nem csak figyelmes, de maximálisan professzionális (és nem mellesleg a humorérzéke is páratlan)!",
				link: "/hu/portre/luca-david/",
			},
			en: {
				name: "Luca P. & Dávid P.",
				excerpt: "He's not only attentive, but highly professional (and by the way, his sense of humour is inimitable)",
				text: "Shooting with Roland was simply fantastic. He's really kind, helpful, and always eager to capture moments in the most creative way. I can happily recommend him. I can guarantee that you'll be in for an extraordinary experience if you're choosing him. He's not only attentive, but highly professional (and by the way, his sense of humour is inimitable)!",
				link: "/en/portraiture/luca-david/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/vivien.webp",
			hu: {
				name: "É. Vivien",
				excerpt: "Roland csodásan megvalósítja azokat a képeket, amiket a fejemben elképzelek",
				text: "Rolival a közös munka mindig jókedvűen és gördülékenyen zajlik, az egész fotózás jó hangulatú. Általában mindig kitalálunk valami kicsit újat és kreatívat. Roland csodásan megvalósítja azokat a képeket, amiket a fejemben elképzelek. Bátran keresem meg kreatívabb, nehezebb kérésekkel is, és mindig valami elképesztő fotósorozat készül belőle. Mindenkinek csak ajánlani tudom.",
				link: "/hu/portre/vivi/",
			},
			en: {
				name: "Vivien É.",
				excerpt: "Roland could make my ideas come to life with ease",
				text: "Working with Roland has always been very fun and smooth, all of our photoshoots took place in a light mood. I could approach him with more creative and difficult concepts and Roland could make my ideas come to life with ease, in the form of staggering photo sets. I can highly recommend him.",
				link: "/en/portraiture/vivi/",
			},
		},
		{
			type: "female",
			score: "5.0",
			photo: "/assets/images/testimonials/viktoria.webp",
			hu: {
				name: "M. Viktória",
				excerpt: "Könnyű volt feloldódni, nem éreztem gátlásosnak magam, sokat viccelődtünk",
				text: "Rolival a fotózásaink hangulata az első pillanattól kezdve laza volt. Könnyű volt feloldódni, nem éreztem gátlásosnak magam, sokat viccelődtünk, amik néha belekontárkodtak egy-egy \"remekműbe\". A zseni hangulatnak köszönhetően a közös munkáinknak kivétel nélkül olyan produktumai születtek, amiket bátran osztottam meg a barátaimmal, illetve a közösségi média felületein.",
				link: "/hu/portre/viki-virag/",
			},
			en: {
				name: "Viktória M.",
				excerpt: "It was easy to relax, I didn't feel inhibited at all, and we've had great laughs that would sometimes break (or make!) a photo",
				text: "The mood of our photoshoots with Roland was super laid-back from the very beginning. It was easy to relax, I didn't feel inhibited at all, and we've had great laughs that would sometimes break (or make!) a photo. Thanks to the chilled vibes, we've made amazing photos that I happily shared with my friends and on social media.",
				link: "/en/portraiture/viki-virag/",
			},
		},
		{
			type: "female",
			score: "",
			photo: "/assets/images/testimonials/kata.webp",
			hu: {
				name: "P. Kata",
				excerpt: "Roland által ki tudtam lépni a komfortzónámból",
				text: "Roland által ki tudtam lépni a komfortzónámból, és a gyönyörűen virágzó fák alatt, az aranyórában készítettük el ezt a csodás sorozatot. Nem mellesleg, kezdő fotósként igazán sok mindent tanulhattam tőle a közös munka során &ndash; mindezt a jövőben alkalmazni is fogom.",
				link: "/hu/portre/kata/",
			},
			en: {
				name: "Kata P.",
				excerpt: "Roland helped me step out of my comfort zone",
				text: "Roland helped me step out of my comfort zone and created this wonderful set under the beautifully blossoming flowers at golden hour. Not to mention, as a beginner photographer, I got to learn lots of new things from him, which I'll certainly use in my upcoming work.",
				link: "/en/portraiture/kata/",
			},
		},
	]
};
